// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_ActionLog.pb.h"

@implementation PpActionLogRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpActionLogRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_ActionLog ()
@property int32_t uid;
@property int32_t actionId;
@property int32_t idNum;
@property int32_t itemNum;
@end

@implementation PP_ActionLog

- (BOOL) hasUid {
  return !!hasUid_;
}
- (void) setHasUid:(BOOL) value_ {
  hasUid_ = !!value_;
}
@synthesize uid;
- (BOOL) hasActionId {
  return !!hasActionId_;
}
- (void) setHasActionId:(BOOL) value_ {
  hasActionId_ = !!value_;
}
@synthesize actionId;
- (BOOL) hasIdNum {
  return !!hasIdNum_;
}
- (void) setHasIdNum:(BOOL) value_ {
  hasIdNum_ = !!value_;
}
@synthesize idNum;
- (BOOL) hasItemNum {
  return !!hasItemNum_;
}
- (void) setHasItemNum:(BOOL) value_ {
  hasItemNum_ = !!value_;
}
@synthesize itemNum;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.uid = 0;
    self.actionId = 0;
    self.idNum = 0;
    self.itemNum = 0;
  }
  return self;
}
static PP_ActionLog* defaultPP_ActionLogInstance = nil;
+ (void) initialize {
  if (self == [PP_ActionLog class]) {
    defaultPP_ActionLogInstance = [[PP_ActionLog alloc] init];
  }
}
+ (PP_ActionLog*) defaultInstance {
  return defaultPP_ActionLogInstance;
}
- (PP_ActionLog*) defaultInstance {
  return defaultPP_ActionLogInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUid) {
    [output writeInt32:1 value:self.uid];
  }
  if (self.hasActionId) {
    [output writeInt32:2 value:self.actionId];
  }
  if (self.hasIdNum) {
    [output writeInt32:3 value:self.idNum];
  }
  if (self.hasItemNum) {
    [output writeInt32:4 value:self.itemNum];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUid) {
    size_ += computeInt32Size(1, self.uid);
  }
  if (self.hasActionId) {
    size_ += computeInt32Size(2, self.actionId);
  }
  if (self.hasIdNum) {
    size_ += computeInt32Size(3, self.idNum);
  }
  if (self.hasItemNum) {
    size_ += computeInt32Size(4, self.itemNum);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_ActionLog*) parseFromData:(NSData*) data {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromData:data] build];
}
+ (PP_ActionLog*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionLog*) parseFromInputStream:(NSInputStream*) input {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromInputStream:input] build];
}
+ (PP_ActionLog*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionLog*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromCodedInputStream:input] build];
}
+ (PP_ActionLog*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionLog*)[[[PP_ActionLog builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionLog_Builder*) builder {
  return [[[PP_ActionLog_Builder alloc] init] autorelease];
}
+ (PP_ActionLog_Builder*) builderWithPrototype:(PP_ActionLog*) prototype {
  return [[PP_ActionLog builder] mergeFrom:prototype];
}
- (PP_ActionLog_Builder*) builder {
  return [PP_ActionLog builder];
}
- (PP_ActionLog_Builder*) toBuilder {
  return [PP_ActionLog builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uid", [NSNumber numberWithInt:self.uid]];
  }
  if (self.hasActionId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"actionId", [NSNumber numberWithInt:self.actionId]];
  }
  if (self.hasIdNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"idNum", [NSNumber numberWithInt:self.idNum]];
  }
  if (self.hasItemNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"itemNum", [NSNumber numberWithInt:self.itemNum]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_ActionLog class]]) {
    return NO;
  }
  PP_ActionLog *otherMessage = other;
  return
      self.hasUid == otherMessage.hasUid &&
      (!self.hasUid || self.uid == otherMessage.uid) &&
      self.hasActionId == otherMessage.hasActionId &&
      (!self.hasActionId || self.actionId == otherMessage.actionId) &&
      self.hasIdNum == otherMessage.hasIdNum &&
      (!self.hasIdNum || self.idNum == otherMessage.idNum) &&
      self.hasItemNum == otherMessage.hasItemNum &&
      (!self.hasItemNum || self.itemNum == otherMessage.itemNum) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasUid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.uid] hash];
  }
  if (self.hasActionId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.actionId] hash];
  }
  if (self.hasIdNum) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.idNum] hash];
  }
  if (self.hasItemNum) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.itemNum] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_ActionLog_Builder()
@property (retain) PP_ActionLog* result;
@end

@implementation PP_ActionLog_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_ActionLog alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_ActionLog_Builder*) clear {
  self.result = [[[PP_ActionLog alloc] init] autorelease];
  return self;
}
- (PP_ActionLog_Builder*) clone {
  return [PP_ActionLog builderWithPrototype:result];
}
- (PP_ActionLog*) defaultInstance {
  return [PP_ActionLog defaultInstance];
}
- (PP_ActionLog*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_ActionLog*) buildPartial {
  PP_ActionLog* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_ActionLog_Builder*) mergeFrom:(PP_ActionLog*) other {
  if (other == [PP_ActionLog defaultInstance]) {
    return self;
  }
  if (other.hasUid) {
    [self setUid:other.uid];
  }
  if (other.hasActionId) {
    [self setActionId:other.actionId];
  }
  if (other.hasIdNum) {
    [self setIdNum:other.idNum];
  }
  if (other.hasItemNum) {
    [self setItemNum:other.itemNum];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_ActionLog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_ActionLog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUid:[input readInt32]];
        break;
      }
      case 16: {
        [self setActionId:[input readInt32]];
        break;
      }
      case 24: {
        [self setIdNum:[input readInt32]];
        break;
      }
      case 32: {
        [self setItemNum:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUid {
  return result.hasUid;
}
- (int32_t) uid {
  return result.uid;
}
- (PP_ActionLog_Builder*) setUid:(int32_t) value {
  result.hasUid = YES;
  result.uid = value;
  return self;
}
- (PP_ActionLog_Builder*) clearUid {
  result.hasUid = NO;
  result.uid = 0;
  return self;
}
- (BOOL) hasActionId {
  return result.hasActionId;
}
- (int32_t) actionId {
  return result.actionId;
}
- (PP_ActionLog_Builder*) setActionId:(int32_t) value {
  result.hasActionId = YES;
  result.actionId = value;
  return self;
}
- (PP_ActionLog_Builder*) clearActionId {
  result.hasActionId = NO;
  result.actionId = 0;
  return self;
}
- (BOOL) hasIdNum {
  return result.hasIdNum;
}
- (int32_t) idNum {
  return result.idNum;
}
- (PP_ActionLog_Builder*) setIdNum:(int32_t) value {
  result.hasIdNum = YES;
  result.idNum = value;
  return self;
}
- (PP_ActionLog_Builder*) clearIdNum {
  result.hasIdNum = NO;
  result.idNum = 0;
  return self;
}
- (BOOL) hasItemNum {
  return result.hasItemNum;
}
- (int32_t) itemNum {
  return result.itemNum;
}
- (PP_ActionLog_Builder*) setItemNum:(int32_t) value {
  result.hasItemNum = YES;
  result.itemNum = value;
  return self;
}
- (PP_ActionLog_Builder*) clearItemNum {
  result.hasItemNum = NO;
  result.itemNum = 0;
  return self;
}
@end

