// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_AttackRes.pb.h"

@class PP_AttackRes;
@class PP_AttackRes_Builder;
@class PP_AttackResult;
@class PP_AttackResult_Builder;
@class PP_GameControl;
@class PP_GameControl_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpAttackResultRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_AttackResult : PBGeneratedMessage {
@private
  PBAppendableArray * attackResArray;
}
@property (readonly, retain) PBArray * attackRes;
- (PP_AttackRes*)attackResAtIndex:(NSUInteger)index;

+ (PP_AttackResult*) defaultInstance;
- (PP_AttackResult*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_AttackResult_Builder*) builder;
+ (PP_AttackResult_Builder*) builder;
+ (PP_AttackResult_Builder*) builderWithPrototype:(PP_AttackResult*) prototype;
- (PP_AttackResult_Builder*) toBuilder;

+ (PP_AttackResult*) parseFromData:(NSData*) data;
+ (PP_AttackResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_AttackResult*) parseFromInputStream:(NSInputStream*) input;
+ (PP_AttackResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_AttackResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_AttackResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_AttackResult_Builder : PBGeneratedMessage_Builder {
@private
  PP_AttackResult* result;
}

- (PP_AttackResult*) defaultInstance;

- (PP_AttackResult_Builder*) clear;
- (PP_AttackResult_Builder*) clone;

- (PP_AttackResult*) build;
- (PP_AttackResult*) buildPartial;

- (PP_AttackResult_Builder*) mergeFrom:(PP_AttackResult*) other;
- (PP_AttackResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_AttackResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)attackRes;
- (PP_AttackRes*)attackResAtIndex:(NSUInteger)index;
- (PP_AttackResult_Builder *)addAttackRes:(PP_AttackRes*)value;
- (PP_AttackResult_Builder *)setAttackResArray:(NSArray *)array;
- (PP_AttackResult_Builder *)setAttackResValues:(const PP_AttackRes* *)values count:(NSUInteger)count;
- (PP_AttackResult_Builder *)clearAttackRes;
@end

