// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_ActionIDs.pb.h"

@implementation PpActionIdsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpActionIdsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_ActionIDs ()
@property int32_t actionId;
@property (retain) NSString* actionName;
@property int32_t createTime;
@end

@implementation PP_ActionIDs

- (BOOL) hasActionId {
  return !!hasActionId_;
}
- (void) setHasActionId:(BOOL) value_ {
  hasActionId_ = !!value_;
}
@synthesize actionId;
- (BOOL) hasActionName {
  return !!hasActionName_;
}
- (void) setHasActionName:(BOOL) value_ {
  hasActionName_ = !!value_;
}
@synthesize actionName;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) value_ {
  hasCreateTime_ = !!value_;
}
@synthesize createTime;
- (void) dealloc {
  self.actionName = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.actionId = 0;
    self.actionName = @"";
    self.createTime = 0;
  }
  return self;
}
static PP_ActionIDs* defaultPP_ActionIDsInstance = nil;
+ (void) initialize {
  if (self == [PP_ActionIDs class]) {
    defaultPP_ActionIDsInstance = [[PP_ActionIDs alloc] init];
  }
}
+ (PP_ActionIDs*) defaultInstance {
  return defaultPP_ActionIDsInstance;
}
- (PP_ActionIDs*) defaultInstance {
  return defaultPP_ActionIDsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasActionId) {
    [output writeInt32:1 value:self.actionId];
  }
  if (self.hasActionName) {
    [output writeString:2 value:self.actionName];
  }
  if (self.hasCreateTime) {
    [output writeInt32:3 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasActionId) {
    size_ += computeInt32Size(1, self.actionId);
  }
  if (self.hasActionName) {
    size_ += computeStringSize(2, self.actionName);
  }
  if (self.hasCreateTime) {
    size_ += computeInt32Size(3, self.createTime);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_ActionIDs*) parseFromData:(NSData*) data {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromData:data] build];
}
+ (PP_ActionIDs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionIDs*) parseFromInputStream:(NSInputStream*) input {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromInputStream:input] build];
}
+ (PP_ActionIDs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionIDs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromCodedInputStream:input] build];
}
+ (PP_ActionIDs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ActionIDs*)[[[PP_ActionIDs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ActionIDs_Builder*) builder {
  return [[[PP_ActionIDs_Builder alloc] init] autorelease];
}
+ (PP_ActionIDs_Builder*) builderWithPrototype:(PP_ActionIDs*) prototype {
  return [[PP_ActionIDs builder] mergeFrom:prototype];
}
- (PP_ActionIDs_Builder*) builder {
  return [PP_ActionIDs builder];
}
- (PP_ActionIDs_Builder*) toBuilder {
  return [PP_ActionIDs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasActionId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"actionId", [NSNumber numberWithInt:self.actionId]];
  }
  if (self.hasActionName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"actionName", self.actionName];
  }
  if (self.hasCreateTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createTime", [NSNumber numberWithInt:self.createTime]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_ActionIDs class]]) {
    return NO;
  }
  PP_ActionIDs *otherMessage = other;
  return
      self.hasActionId == otherMessage.hasActionId &&
      (!self.hasActionId || self.actionId == otherMessage.actionId) &&
      self.hasActionName == otherMessage.hasActionName &&
      (!self.hasActionName || [self.actionName isEqual:otherMessage.actionName]) &&
      self.hasCreateTime == otherMessage.hasCreateTime &&
      (!self.hasCreateTime || self.createTime == otherMessage.createTime) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasActionId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.actionId] hash];
  }
  if (self.hasActionName) {
    hashCode = hashCode * 31 + [self.actionName hash];
  }
  if (self.hasCreateTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.createTime] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_ActionIDs_Builder()
@property (retain) PP_ActionIDs* result;
@end

@implementation PP_ActionIDs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_ActionIDs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_ActionIDs_Builder*) clear {
  self.result = [[[PP_ActionIDs alloc] init] autorelease];
  return self;
}
- (PP_ActionIDs_Builder*) clone {
  return [PP_ActionIDs builderWithPrototype:result];
}
- (PP_ActionIDs*) defaultInstance {
  return [PP_ActionIDs defaultInstance];
}
- (PP_ActionIDs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_ActionIDs*) buildPartial {
  PP_ActionIDs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_ActionIDs_Builder*) mergeFrom:(PP_ActionIDs*) other {
  if (other == [PP_ActionIDs defaultInstance]) {
    return self;
  }
  if (other.hasActionId) {
    [self setActionId:other.actionId];
  }
  if (other.hasActionName) {
    [self setActionName:other.actionName];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_ActionIDs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_ActionIDs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setActionId:[input readInt32]];
        break;
      }
      case 18: {
        [self setActionName:[input readString]];
        break;
      }
      case 24: {
        [self setCreateTime:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasActionId {
  return result.hasActionId;
}
- (int32_t) actionId {
  return result.actionId;
}
- (PP_ActionIDs_Builder*) setActionId:(int32_t) value {
  result.hasActionId = YES;
  result.actionId = value;
  return self;
}
- (PP_ActionIDs_Builder*) clearActionId {
  result.hasActionId = NO;
  result.actionId = 0;
  return self;
}
- (BOOL) hasActionName {
  return result.hasActionName;
}
- (NSString*) actionName {
  return result.actionName;
}
- (PP_ActionIDs_Builder*) setActionName:(NSString*) value {
  result.hasActionName = YES;
  result.actionName = value;
  return self;
}
- (PP_ActionIDs_Builder*) clearActionName {
  result.hasActionName = NO;
  result.actionName = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return result.hasCreateTime;
}
- (int32_t) createTime {
  return result.createTime;
}
- (PP_ActionIDs_Builder*) setCreateTime:(int32_t) value {
  result.hasCreateTime = YES;
  result.createTime = value;
  return self;
}
- (PP_ActionIDs_Builder*) clearCreateTime {
  result.hasCreateTime = NO;
  result.createTime = 0;
  return self;
}
@end

