// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_ActionIDs;
@class PP_ActionIDs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpActionIdsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_ActionIDs : PBGeneratedMessage {
@private
  BOOL hasActionId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasActionName_:1;
  int32_t actionId;
  int32_t createTime;
  NSString* actionName;
}
- (BOOL) hasActionId;
- (BOOL) hasActionName;
- (BOOL) hasCreateTime;
@property (readonly) int32_t actionId;
@property (readonly, retain) NSString* actionName;
@property (readonly) int32_t createTime;

+ (PP_ActionIDs*) defaultInstance;
- (PP_ActionIDs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_ActionIDs_Builder*) builder;
+ (PP_ActionIDs_Builder*) builder;
+ (PP_ActionIDs_Builder*) builderWithPrototype:(PP_ActionIDs*) prototype;
- (PP_ActionIDs_Builder*) toBuilder;

+ (PP_ActionIDs*) parseFromData:(NSData*) data;
+ (PP_ActionIDs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ActionIDs*) parseFromInputStream:(NSInputStream*) input;
+ (PP_ActionIDs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ActionIDs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_ActionIDs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_ActionIDs_Builder : PBGeneratedMessage_Builder {
@private
  PP_ActionIDs* result;
}

- (PP_ActionIDs*) defaultInstance;

- (PP_ActionIDs_Builder*) clear;
- (PP_ActionIDs_Builder*) clone;

- (PP_ActionIDs*) build;
- (PP_ActionIDs*) buildPartial;

- (PP_ActionIDs_Builder*) mergeFrom:(PP_ActionIDs*) other;
- (PP_ActionIDs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_ActionIDs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasActionId;
- (int32_t) actionId;
- (PP_ActionIDs_Builder*) setActionId:(int32_t) value;
- (PP_ActionIDs_Builder*) clearActionId;

- (BOOL) hasActionName;
- (NSString*) actionName;
- (PP_ActionIDs_Builder*) setActionName:(NSString*) value;
- (PP_ActionIDs_Builder*) clearActionName;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_ActionIDs_Builder*) setCreateTime:(int32_t) value;
- (PP_ActionIDs_Builder*) clearCreateTime;
@end

