// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_AttackResult.pb.h"

@implementation PpAttackResultRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpAttackResultRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [PpAttackResRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_AttackResult ()
@property (retain) PBAppendableArray * attackResArray;
@end

@implementation PP_AttackResult

@synthesize attackResArray;
@dynamic attackRes;
- (void) dealloc {
  self.attackResArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static PP_AttackResult* defaultPP_AttackResultInstance = nil;
+ (void) initialize {
  if (self == [PP_AttackResult class]) {
    defaultPP_AttackResultInstance = [[PP_AttackResult alloc] init];
  }
}
+ (PP_AttackResult*) defaultInstance {
  return defaultPP_AttackResultInstance;
}
- (PP_AttackResult*) defaultInstance {
  return defaultPP_AttackResultInstance;
}
- (PBArray *)attackRes {
  return attackResArray;
}
- (PP_AttackRes*)attackResAtIndex:(NSUInteger)index {
  return [attackResArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (PP_AttackRes *element in self.attackResArray) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  for (PP_AttackRes *element in self.attackResArray) {
    size_ += computeMessageSize(1, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_AttackResult*) parseFromData:(NSData*) data {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromData:data] build];
}
+ (PP_AttackResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_AttackResult*) parseFromInputStream:(NSInputStream*) input {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromInputStream:input] build];
}
+ (PP_AttackResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_AttackResult*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromCodedInputStream:input] build];
}
+ (PP_AttackResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_AttackResult*)[[[PP_AttackResult builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_AttackResult_Builder*) builder {
  return [[[PP_AttackResult_Builder alloc] init] autorelease];
}
+ (PP_AttackResult_Builder*) builderWithPrototype:(PP_AttackResult*) prototype {
  return [[PP_AttackResult builder] mergeFrom:prototype];
}
- (PP_AttackResult_Builder*) builder {
  return [PP_AttackResult builder];
}
- (PP_AttackResult_Builder*) toBuilder {
  return [PP_AttackResult builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  for (PP_AttackRes* element in self.attackResArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"attackRes"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_AttackResult class]]) {
    return NO;
  }
  PP_AttackResult *otherMessage = other;
  return
      [self.attackResArray isEqualToArray:otherMessage.attackResArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  for (PP_AttackRes* element in self.attackResArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_AttackResult_Builder()
@property (retain) PP_AttackResult* result;
@end

@implementation PP_AttackResult_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_AttackResult alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_AttackResult_Builder*) clear {
  self.result = [[[PP_AttackResult alloc] init] autorelease];
  return self;
}
- (PP_AttackResult_Builder*) clone {
  return [PP_AttackResult builderWithPrototype:result];
}
- (PP_AttackResult*) defaultInstance {
  return [PP_AttackResult defaultInstance];
}
- (PP_AttackResult*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_AttackResult*) buildPartial {
  PP_AttackResult* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_AttackResult_Builder*) mergeFrom:(PP_AttackResult*) other {
  if (other == [PP_AttackResult defaultInstance]) {
    return self;
  }
  if (other.attackResArray.count > 0) {
    if (result.attackResArray == nil) {
      result.attackResArray = [[other.attackResArray copyWithZone:[other.attackResArray zone]] autorelease];
    } else {
      [result.attackResArray appendArray:other.attackResArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_AttackResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_AttackResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PP_AttackRes_Builder* subBuilder = [PP_AttackRes builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addAttackRes:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (PBAppendableArray *)attackRes {
  return result.attackResArray;
}
- (PP_AttackRes*)attackResAtIndex:(NSUInteger)index {
  return [result attackResAtIndex:index];
}
- (PP_AttackResult_Builder *)addAttackRes:(PP_AttackRes*)value {
  if (result.attackResArray == nil) {
    result.attackResArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.attackResArray addObject:value];
  return self;
}
- (PP_AttackResult_Builder *)setAttackResArray:(NSArray *)array {
  result.attackResArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (PP_AttackResult_Builder *)setAttackResValues:(const PP_AttackRes* *)values count:(NSUInteger)count {
  result.attackResArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (PP_AttackResult_Builder *)clearAttackRes {
  result.attackResArray = nil;
  return self;
}
@end

