// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_ChildSkillData;
@class PP_ChildSkillData_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpChildSkillDataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_ChildSkillData : PBGeneratedMessage {
@private
  BOOL hasSkillId_:1;
  BOOL hasItemId_:1;
  BOOL hasItemNum_:1;
  int32_t skillId;
  int32_t itemId;
  int32_t itemNum;
}
- (BOOL) hasSkillId;
- (BOOL) hasItemId;
- (BOOL) hasItemNum;
@property (readonly) int32_t skillId;
@property (readonly) int32_t itemId;
@property (readonly) int32_t itemNum;

+ (PP_ChildSkillData*) defaultInstance;
- (PP_ChildSkillData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_ChildSkillData_Builder*) builder;
+ (PP_ChildSkillData_Builder*) builder;
+ (PP_ChildSkillData_Builder*) builderWithPrototype:(PP_ChildSkillData*) prototype;
- (PP_ChildSkillData_Builder*) toBuilder;

+ (PP_ChildSkillData*) parseFromData:(NSData*) data;
+ (PP_ChildSkillData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ChildSkillData*) parseFromInputStream:(NSInputStream*) input;
+ (PP_ChildSkillData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ChildSkillData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_ChildSkillData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_ChildSkillData_Builder : PBGeneratedMessage_Builder {
@private
  PP_ChildSkillData* result;
}

- (PP_ChildSkillData*) defaultInstance;

- (PP_ChildSkillData_Builder*) clear;
- (PP_ChildSkillData_Builder*) clone;

- (PP_ChildSkillData*) build;
- (PP_ChildSkillData*) buildPartial;

- (PP_ChildSkillData_Builder*) mergeFrom:(PP_ChildSkillData*) other;
- (PP_ChildSkillData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_ChildSkillData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSkillId;
- (int32_t) skillId;
- (PP_ChildSkillData_Builder*) setSkillId:(int32_t) value;
- (PP_ChildSkillData_Builder*) clearSkillId;

- (BOOL) hasItemId;
- (int32_t) itemId;
- (PP_ChildSkillData_Builder*) setItemId:(int32_t) value;
- (PP_ChildSkillData_Builder*) clearItemId;

- (BOOL) hasItemNum;
- (int32_t) itemNum;
- (PP_ChildSkillData_Builder*) setItemNum:(int32_t) value;
- (PP_ChildSkillData_Builder*) clearItemNum;
@end

