// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Formula;
@class PP_Formula_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpFormulaRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Formula : PBGeneratedMessage {
@private
  BOOL hasFormulaId_:1;
  BOOL hasUid_:1;
  BOOL hasSkillId_:1;
  BOOL hasVersionId_:1;
  BOOL hasCreateTime_:1;
  int32_t formulaId;
  int32_t uid;
  int32_t skillId;
  int32_t versionId;
  int32_t createTime;
}
- (BOOL) hasFormulaId;
- (BOOL) hasUid;
- (BOOL) hasSkillId;
- (BOOL) hasVersionId;
- (BOOL) hasCreateTime;
@property (readonly) int32_t formulaId;
@property (readonly) int32_t uid;
@property (readonly) int32_t skillId;
@property (readonly) int32_t versionId;
@property (readonly) int32_t createTime;

+ (PP_Formula*) defaultInstance;
- (PP_Formula*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Formula_Builder*) builder;
+ (PP_Formula_Builder*) builder;
+ (PP_Formula_Builder*) builderWithPrototype:(PP_Formula*) prototype;
- (PP_Formula_Builder*) toBuilder;

+ (PP_Formula*) parseFromData:(NSData*) data;
+ (PP_Formula*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Formula*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Formula*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Formula*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Formula*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Formula_Builder : PBGeneratedMessage_Builder {
@private
  PP_Formula* result;
}

- (PP_Formula*) defaultInstance;

- (PP_Formula_Builder*) clear;
- (PP_Formula_Builder*) clone;

- (PP_Formula*) build;
- (PP_Formula*) buildPartial;

- (PP_Formula_Builder*) mergeFrom:(PP_Formula*) other;
- (PP_Formula_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Formula_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFormulaId;
- (int32_t) formulaId;
- (PP_Formula_Builder*) setFormulaId:(int32_t) value;
- (PP_Formula_Builder*) clearFormulaId;

- (BOOL) hasUid;
- (int32_t) uid;
- (PP_Formula_Builder*) setUid:(int32_t) value;
- (PP_Formula_Builder*) clearUid;

- (BOOL) hasSkillId;
- (int32_t) skillId;
- (PP_Formula_Builder*) setSkillId:(int32_t) value;
- (PP_Formula_Builder*) clearSkillId;

- (BOOL) hasVersionId;
- (int32_t) versionId;
- (PP_Formula_Builder*) setVersionId:(int32_t) value;
- (PP_Formula_Builder*) clearVersionId;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_Formula_Builder*) setCreateTime:(int32_t) value;
- (PP_Formula_Builder*) clearCreateTime;
@end

