// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_Formula.pb.h"

@implementation PpFormulaRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpFormulaRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_Formula ()
@property int32_t formulaId;
@property int32_t uid;
@property int32_t skillId;
@property int32_t versionId;
@property int32_t createTime;
@end

@implementation PP_Formula

- (BOOL) hasFormulaId {
  return !!hasFormulaId_;
}
- (void) setHasFormulaId:(BOOL) value_ {
  hasFormulaId_ = !!value_;
}
@synthesize formulaId;
- (BOOL) hasUid {
  return !!hasUid_;
}
- (void) setHasUid:(BOOL) value_ {
  hasUid_ = !!value_;
}
@synthesize uid;
- (BOOL) hasSkillId {
  return !!hasSkillId_;
}
- (void) setHasSkillId:(BOOL) value_ {
  hasSkillId_ = !!value_;
}
@synthesize skillId;
- (BOOL) hasVersionId {
  return !!hasVersionId_;
}
- (void) setHasVersionId:(BOOL) value_ {
  hasVersionId_ = !!value_;
}
@synthesize versionId;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) value_ {
  hasCreateTime_ = !!value_;
}
@synthesize createTime;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.formulaId = 0;
    self.uid = 0;
    self.skillId = 0;
    self.versionId = 0;
    self.createTime = 0;
  }
  return self;
}
static PP_Formula* defaultPP_FormulaInstance = nil;
+ (void) initialize {
  if (self == [PP_Formula class]) {
    defaultPP_FormulaInstance = [[PP_Formula alloc] init];
  }
}
+ (PP_Formula*) defaultInstance {
  return defaultPP_FormulaInstance;
}
- (PP_Formula*) defaultInstance {
  return defaultPP_FormulaInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasFormulaId) {
    [output writeInt32:1 value:self.formulaId];
  }
  if (self.hasUid) {
    [output writeInt32:2 value:self.uid];
  }
  if (self.hasSkillId) {
    [output writeInt32:3 value:self.skillId];
  }
  if (self.hasVersionId) {
    [output writeInt32:4 value:self.versionId];
  }
  if (self.hasCreateTime) {
    [output writeInt32:5 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasFormulaId) {
    size_ += computeInt32Size(1, self.formulaId);
  }
  if (self.hasUid) {
    size_ += computeInt32Size(2, self.uid);
  }
  if (self.hasSkillId) {
    size_ += computeInt32Size(3, self.skillId);
  }
  if (self.hasVersionId) {
    size_ += computeInt32Size(4, self.versionId);
  }
  if (self.hasCreateTime) {
    size_ += computeInt32Size(5, self.createTime);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_Formula*) parseFromData:(NSData*) data {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromData:data] build];
}
+ (PP_Formula*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_Formula*) parseFromInputStream:(NSInputStream*) input {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromInputStream:input] build];
}
+ (PP_Formula*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_Formula*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromCodedInputStream:input] build];
}
+ (PP_Formula*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Formula*)[[[PP_Formula builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_Formula_Builder*) builder {
  return [[[PP_Formula_Builder alloc] init] autorelease];
}
+ (PP_Formula_Builder*) builderWithPrototype:(PP_Formula*) prototype {
  return [[PP_Formula builder] mergeFrom:prototype];
}
- (PP_Formula_Builder*) builder {
  return [PP_Formula builder];
}
- (PP_Formula_Builder*) toBuilder {
  return [PP_Formula builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasFormulaId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"formulaId", [NSNumber numberWithInt:self.formulaId]];
  }
  if (self.hasUid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uid", [NSNumber numberWithInt:self.uid]];
  }
  if (self.hasSkillId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"skillId", [NSNumber numberWithInt:self.skillId]];
  }
  if (self.hasVersionId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"versionId", [NSNumber numberWithInt:self.versionId]];
  }
  if (self.hasCreateTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createTime", [NSNumber numberWithInt:self.createTime]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_Formula class]]) {
    return NO;
  }
  PP_Formula *otherMessage = other;
  return
      self.hasFormulaId == otherMessage.hasFormulaId &&
      (!self.hasFormulaId || self.formulaId == otherMessage.formulaId) &&
      self.hasUid == otherMessage.hasUid &&
      (!self.hasUid || self.uid == otherMessage.uid) &&
      self.hasSkillId == otherMessage.hasSkillId &&
      (!self.hasSkillId || self.skillId == otherMessage.skillId) &&
      self.hasVersionId == otherMessage.hasVersionId &&
      (!self.hasVersionId || self.versionId == otherMessage.versionId) &&
      self.hasCreateTime == otherMessage.hasCreateTime &&
      (!self.hasCreateTime || self.createTime == otherMessage.createTime) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasFormulaId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.formulaId] hash];
  }
  if (self.hasUid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.uid] hash];
  }
  if (self.hasSkillId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.skillId] hash];
  }
  if (self.hasVersionId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.versionId] hash];
  }
  if (self.hasCreateTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.createTime] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_Formula_Builder()
@property (retain) PP_Formula* result;
@end

@implementation PP_Formula_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_Formula alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_Formula_Builder*) clear {
  self.result = [[[PP_Formula alloc] init] autorelease];
  return self;
}
- (PP_Formula_Builder*) clone {
  return [PP_Formula builderWithPrototype:result];
}
- (PP_Formula*) defaultInstance {
  return [PP_Formula defaultInstance];
}
- (PP_Formula*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_Formula*) buildPartial {
  PP_Formula* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_Formula_Builder*) mergeFrom:(PP_Formula*) other {
  if (other == [PP_Formula defaultInstance]) {
    return self;
  }
  if (other.hasFormulaId) {
    [self setFormulaId:other.formulaId];
  }
  if (other.hasUid) {
    [self setUid:other.uid];
  }
  if (other.hasSkillId) {
    [self setSkillId:other.skillId];
  }
  if (other.hasVersionId) {
    [self setVersionId:other.versionId];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_Formula_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_Formula_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setFormulaId:[input readInt32]];
        break;
      }
      case 16: {
        [self setUid:[input readInt32]];
        break;
      }
      case 24: {
        [self setSkillId:[input readInt32]];
        break;
      }
      case 32: {
        [self setVersionId:[input readInt32]];
        break;
      }
      case 40: {
        [self setCreateTime:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasFormulaId {
  return result.hasFormulaId;
}
- (int32_t) formulaId {
  return result.formulaId;
}
- (PP_Formula_Builder*) setFormulaId:(int32_t) value {
  result.hasFormulaId = YES;
  result.formulaId = value;
  return self;
}
- (PP_Formula_Builder*) clearFormulaId {
  result.hasFormulaId = NO;
  result.formulaId = 0;
  return self;
}
- (BOOL) hasUid {
  return result.hasUid;
}
- (int32_t) uid {
  return result.uid;
}
- (PP_Formula_Builder*) setUid:(int32_t) value {
  result.hasUid = YES;
  result.uid = value;
  return self;
}
- (PP_Formula_Builder*) clearUid {
  result.hasUid = NO;
  result.uid = 0;
  return self;
}
- (BOOL) hasSkillId {
  return result.hasSkillId;
}
- (int32_t) skillId {
  return result.skillId;
}
- (PP_Formula_Builder*) setSkillId:(int32_t) value {
  result.hasSkillId = YES;
  result.skillId = value;
  return self;
}
- (PP_Formula_Builder*) clearSkillId {
  result.hasSkillId = NO;
  result.skillId = 0;
  return self;
}
- (BOOL) hasVersionId {
  return result.hasVersionId;
}
- (int32_t) versionId {
  return result.versionId;
}
- (PP_Formula_Builder*) setVersionId:(int32_t) value {
  result.hasVersionId = YES;
  result.versionId = value;
  return self;
}
- (PP_Formula_Builder*) clearVersionId {
  result.hasVersionId = NO;
  result.versionId = 0;
  return self;
}
- (BOOL) hasCreateTime {
  return result.hasCreateTime;
}
- (int32_t) createTime {
  return result.createTime;
}
- (PP_Formula_Builder*) setCreateTime:(int32_t) value {
  result.hasCreateTime = YES;
  result.createTime = value;
  return self;
}
- (PP_Formula_Builder*) clearCreateTime {
  result.hasCreateTime = NO;
  result.createTime = 0;
  return self;
}
@end

