// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Location;
@class PP_Location_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpLocationRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Location : PBGeneratedMessage {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  Float64 latitude;
  Float64 longitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly) Float64 latitude;
@property (readonly) Float64 longitude;

+ (PP_Location*) defaultInstance;
- (PP_Location*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Location_Builder*) builder;
+ (PP_Location_Builder*) builder;
+ (PP_Location_Builder*) builderWithPrototype:(PP_Location*) prototype;
- (PP_Location_Builder*) toBuilder;

+ (PP_Location*) parseFromData:(NSData*) data;
+ (PP_Location*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Location*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Location*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Location*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Location*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Location_Builder : PBGeneratedMessage_Builder {
@private
  PP_Location* result;
}

- (PP_Location*) defaultInstance;

- (PP_Location_Builder*) clear;
- (PP_Location_Builder*) clone;

- (PP_Location*) build;
- (PP_Location*) buildPartial;

- (PP_Location_Builder*) mergeFrom:(PP_Location*) other;
- (PP_Location_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Location_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (PP_Location_Builder*) setLatitude:(Float64) value;
- (PP_Location_Builder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (PP_Location_Builder*) setLongitude:(Float64) value;
- (PP_Location_Builder*) clearLongitude;
@end

