// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_LoginPack.pb.h"

@implementation PpLoginPackRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpLoginPackRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [PpAccountRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_LoginPack ()
@property (retain) PP_Account* account;
@property int32_t loginMode;
@property int32_t version;
@property int32_t bagVersion;
@property int32_t relationshipVersion;
@property int32_t equipVersion;
@property int32_t petVersion;
@property int32_t resVersion;
@property int32_t finishVersion;
@property int32_t unfinishVersion;
@property (retain) NSString* duid;
@end

@implementation PP_LoginPack

- (BOOL) hasAccount {
  return !!hasAccount_;
}
- (void) setHasAccount:(BOOL) value_ {
  hasAccount_ = !!value_;
}
@synthesize account;
- (BOOL) hasLoginMode {
  return !!hasLoginMode_;
}
- (void) setHasLoginMode:(BOOL) value_ {
  hasLoginMode_ = !!value_;
}
@synthesize loginMode;
- (BOOL) hasVersion {
  return !!hasVersion_;
}
- (void) setHasVersion:(BOOL) value_ {
  hasVersion_ = !!value_;
}
@synthesize version;
- (BOOL) hasBagVersion {
  return !!hasBagVersion_;
}
- (void) setHasBagVersion:(BOOL) value_ {
  hasBagVersion_ = !!value_;
}
@synthesize bagVersion;
- (BOOL) hasRelationshipVersion {
  return !!hasRelationshipVersion_;
}
- (void) setHasRelationshipVersion:(BOOL) value_ {
  hasRelationshipVersion_ = !!value_;
}
@synthesize relationshipVersion;
- (BOOL) hasEquipVersion {
  return !!hasEquipVersion_;
}
- (void) setHasEquipVersion:(BOOL) value_ {
  hasEquipVersion_ = !!value_;
}
@synthesize equipVersion;
- (BOOL) hasPetVersion {
  return !!hasPetVersion_;
}
- (void) setHasPetVersion:(BOOL) value_ {
  hasPetVersion_ = !!value_;
}
@synthesize petVersion;
- (BOOL) hasResVersion {
  return !!hasResVersion_;
}
- (void) setHasResVersion:(BOOL) value_ {
  hasResVersion_ = !!value_;
}
@synthesize resVersion;
- (BOOL) hasFinishVersion {
  return !!hasFinishVersion_;
}
- (void) setHasFinishVersion:(BOOL) value_ {
  hasFinishVersion_ = !!value_;
}
@synthesize finishVersion;
- (BOOL) hasUnfinishVersion {
  return !!hasUnfinishVersion_;
}
- (void) setHasUnfinishVersion:(BOOL) value_ {
  hasUnfinishVersion_ = !!value_;
}
@synthesize unfinishVersion;
- (BOOL) hasDuid {
  return !!hasDuid_;
}
- (void) setHasDuid:(BOOL) value_ {
  hasDuid_ = !!value_;
}
@synthesize duid;
- (void) dealloc {
  self.account = nil;
  self.duid = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.account = [PP_Account defaultInstance];
    self.loginMode = 0;
    self.version = 0;
    self.bagVersion = 0;
    self.relationshipVersion = 0;
    self.equipVersion = 0;
    self.petVersion = 0;
    self.resVersion = 0;
    self.finishVersion = 0;
    self.unfinishVersion = 0;
    self.duid = @"";
  }
  return self;
}
static PP_LoginPack* defaultPP_LoginPackInstance = nil;
+ (void) initialize {
  if (self == [PP_LoginPack class]) {
    defaultPP_LoginPackInstance = [[PP_LoginPack alloc] init];
  }
}
+ (PP_LoginPack*) defaultInstance {
  return defaultPP_LoginPackInstance;
}
- (PP_LoginPack*) defaultInstance {
  return defaultPP_LoginPackInstance;
}
- (BOOL) isInitialized {
  if (!self.hasAccount) {
    return NO;
  }
  if (!self.hasLoginMode) {
    return NO;
  }
  if (!self.account.isInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAccount) {
    [output writeMessage:1 value:self.account];
  }
  if (self.hasLoginMode) {
    [output writeInt32:2 value:self.loginMode];
  }
  if (self.hasVersion) {
    [output writeInt32:3 value:self.version];
  }
  if (self.hasBagVersion) {
    [output writeInt32:4 value:self.bagVersion];
  }
  if (self.hasRelationshipVersion) {
    [output writeInt32:5 value:self.relationshipVersion];
  }
  if (self.hasEquipVersion) {
    [output writeInt32:6 value:self.equipVersion];
  }
  if (self.hasPetVersion) {
    [output writeInt32:7 value:self.petVersion];
  }
  if (self.hasResVersion) {
    [output writeInt32:8 value:self.resVersion];
  }
  if (self.hasFinishVersion) {
    [output writeInt32:9 value:self.finishVersion];
  }
  if (self.hasUnfinishVersion) {
    [output writeInt32:10 value:self.unfinishVersion];
  }
  if (self.hasDuid) {
    [output writeString:11 value:self.duid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasAccount) {
    size_ += computeMessageSize(1, self.account);
  }
  if (self.hasLoginMode) {
    size_ += computeInt32Size(2, self.loginMode);
  }
  if (self.hasVersion) {
    size_ += computeInt32Size(3, self.version);
  }
  if (self.hasBagVersion) {
    size_ += computeInt32Size(4, self.bagVersion);
  }
  if (self.hasRelationshipVersion) {
    size_ += computeInt32Size(5, self.relationshipVersion);
  }
  if (self.hasEquipVersion) {
    size_ += computeInt32Size(6, self.equipVersion);
  }
  if (self.hasPetVersion) {
    size_ += computeInt32Size(7, self.petVersion);
  }
  if (self.hasResVersion) {
    size_ += computeInt32Size(8, self.resVersion);
  }
  if (self.hasFinishVersion) {
    size_ += computeInt32Size(9, self.finishVersion);
  }
  if (self.hasUnfinishVersion) {
    size_ += computeInt32Size(10, self.unfinishVersion);
  }
  if (self.hasDuid) {
    size_ += computeStringSize(11, self.duid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_LoginPack*) parseFromData:(NSData*) data {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromData:data] build];
}
+ (PP_LoginPack*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_LoginPack*) parseFromInputStream:(NSInputStream*) input {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromInputStream:input] build];
}
+ (PP_LoginPack*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_LoginPack*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromCodedInputStream:input] build];
}
+ (PP_LoginPack*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_LoginPack*)[[[PP_LoginPack builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_LoginPack_Builder*) builder {
  return [[[PP_LoginPack_Builder alloc] init] autorelease];
}
+ (PP_LoginPack_Builder*) builderWithPrototype:(PP_LoginPack*) prototype {
  return [[PP_LoginPack builder] mergeFrom:prototype];
}
- (PP_LoginPack_Builder*) builder {
  return [PP_LoginPack builder];
}
- (PP_LoginPack_Builder*) toBuilder {
  return [PP_LoginPack builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasAccount) {
    [output appendFormat:@"%@%@ {\n", indent, @"account"];
    [self.account writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasLoginMode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"loginMode", [NSNumber numberWithInt:self.loginMode]];
  }
  if (self.hasVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"version", [NSNumber numberWithInt:self.version]];
  }
  if (self.hasBagVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bagVersion", [NSNumber numberWithInt:self.bagVersion]];
  }
  if (self.hasRelationshipVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"relationshipVersion", [NSNumber numberWithInt:self.relationshipVersion]];
  }
  if (self.hasEquipVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"equipVersion", [NSNumber numberWithInt:self.equipVersion]];
  }
  if (self.hasPetVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"petVersion", [NSNumber numberWithInt:self.petVersion]];
  }
  if (self.hasResVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resVersion", [NSNumber numberWithInt:self.resVersion]];
  }
  if (self.hasFinishVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"finishVersion", [NSNumber numberWithInt:self.finishVersion]];
  }
  if (self.hasUnfinishVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"unfinishVersion", [NSNumber numberWithInt:self.unfinishVersion]];
  }
  if (self.hasDuid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"duid", self.duid];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_LoginPack class]]) {
    return NO;
  }
  PP_LoginPack *otherMessage = other;
  return
      self.hasAccount == otherMessage.hasAccount &&
      (!self.hasAccount || [self.account isEqual:otherMessage.account]) &&
      self.hasLoginMode == otherMessage.hasLoginMode &&
      (!self.hasLoginMode || self.loginMode == otherMessage.loginMode) &&
      self.hasVersion == otherMessage.hasVersion &&
      (!self.hasVersion || self.version == otherMessage.version) &&
      self.hasBagVersion == otherMessage.hasBagVersion &&
      (!self.hasBagVersion || self.bagVersion == otherMessage.bagVersion) &&
      self.hasRelationshipVersion == otherMessage.hasRelationshipVersion &&
      (!self.hasRelationshipVersion || self.relationshipVersion == otherMessage.relationshipVersion) &&
      self.hasEquipVersion == otherMessage.hasEquipVersion &&
      (!self.hasEquipVersion || self.equipVersion == otherMessage.equipVersion) &&
      self.hasPetVersion == otherMessage.hasPetVersion &&
      (!self.hasPetVersion || self.petVersion == otherMessage.petVersion) &&
      self.hasResVersion == otherMessage.hasResVersion &&
      (!self.hasResVersion || self.resVersion == otherMessage.resVersion) &&
      self.hasFinishVersion == otherMessage.hasFinishVersion &&
      (!self.hasFinishVersion || self.finishVersion == otherMessage.finishVersion) &&
      self.hasUnfinishVersion == otherMessage.hasUnfinishVersion &&
      (!self.hasUnfinishVersion || self.unfinishVersion == otherMessage.unfinishVersion) &&
      self.hasDuid == otherMessage.hasDuid &&
      (!self.hasDuid || [self.duid isEqual:otherMessage.duid]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasAccount) {
    hashCode = hashCode * 31 + [self.account hash];
  }
  if (self.hasLoginMode) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.loginMode] hash];
  }
  if (self.hasVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.version] hash];
  }
  if (self.hasBagVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.bagVersion] hash];
  }
  if (self.hasRelationshipVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.relationshipVersion] hash];
  }
  if (self.hasEquipVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.equipVersion] hash];
  }
  if (self.hasPetVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.petVersion] hash];
  }
  if (self.hasResVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.resVersion] hash];
  }
  if (self.hasFinishVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.finishVersion] hash];
  }
  if (self.hasUnfinishVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.unfinishVersion] hash];
  }
  if (self.hasDuid) {
    hashCode = hashCode * 31 + [self.duid hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_LoginPack_Builder()
@property (retain) PP_LoginPack* result;
@end

@implementation PP_LoginPack_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_LoginPack alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_LoginPack_Builder*) clear {
  self.result = [[[PP_LoginPack alloc] init] autorelease];
  return self;
}
- (PP_LoginPack_Builder*) clone {
  return [PP_LoginPack builderWithPrototype:result];
}
- (PP_LoginPack*) defaultInstance {
  return [PP_LoginPack defaultInstance];
}
- (PP_LoginPack*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_LoginPack*) buildPartial {
  PP_LoginPack* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_LoginPack_Builder*) mergeFrom:(PP_LoginPack*) other {
  if (other == [PP_LoginPack defaultInstance]) {
    return self;
  }
  if (other.hasAccount) {
    [self mergeAccount:other.account];
  }
  if (other.hasLoginMode) {
    [self setLoginMode:other.loginMode];
  }
  if (other.hasVersion) {
    [self setVersion:other.version];
  }
  if (other.hasBagVersion) {
    [self setBagVersion:other.bagVersion];
  }
  if (other.hasRelationshipVersion) {
    [self setRelationshipVersion:other.relationshipVersion];
  }
  if (other.hasEquipVersion) {
    [self setEquipVersion:other.equipVersion];
  }
  if (other.hasPetVersion) {
    [self setPetVersion:other.petVersion];
  }
  if (other.hasResVersion) {
    [self setResVersion:other.resVersion];
  }
  if (other.hasFinishVersion) {
    [self setFinishVersion:other.finishVersion];
  }
  if (other.hasUnfinishVersion) {
    [self setUnfinishVersion:other.unfinishVersion];
  }
  if (other.hasDuid) {
    [self setDuid:other.duid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_LoginPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_LoginPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PP_Account_Builder* subBuilder = [PP_Account builder];
        if (self.hasAccount) {
          [subBuilder mergeFrom:self.account];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setAccount:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        [self setLoginMode:[input readInt32]];
        break;
      }
      case 24: {
        [self setVersion:[input readInt32]];
        break;
      }
      case 32: {
        [self setBagVersion:[input readInt32]];
        break;
      }
      case 40: {
        [self setRelationshipVersion:[input readInt32]];
        break;
      }
      case 48: {
        [self setEquipVersion:[input readInt32]];
        break;
      }
      case 56: {
        [self setPetVersion:[input readInt32]];
        break;
      }
      case 64: {
        [self setResVersion:[input readInt32]];
        break;
      }
      case 72: {
        [self setFinishVersion:[input readInt32]];
        break;
      }
      case 80: {
        [self setUnfinishVersion:[input readInt32]];
        break;
      }
      case 90: {
        [self setDuid:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAccount {
  return result.hasAccount;
}
- (PP_Account*) account {
  return result.account;
}
- (PP_LoginPack_Builder*) setAccount:(PP_Account*) value {
  result.hasAccount = YES;
  result.account = value;
  return self;
}
- (PP_LoginPack_Builder*) setAccountBuilder:(PP_Account_Builder*) builderForValue {
  return [self setAccount:[builderForValue build]];
}
- (PP_LoginPack_Builder*) mergeAccount:(PP_Account*) value {
  if (result.hasAccount &&
      result.account != [PP_Account defaultInstance]) {
    result.account =
      [[[PP_Account builderWithPrototype:result.account] mergeFrom:value] buildPartial];
  } else {
    result.account = value;
  }
  result.hasAccount = YES;
  return self;
}
- (PP_LoginPack_Builder*) clearAccount {
  result.hasAccount = NO;
  result.account = [PP_Account defaultInstance];
  return self;
}
- (BOOL) hasLoginMode {
  return result.hasLoginMode;
}
- (int32_t) loginMode {
  return result.loginMode;
}
- (PP_LoginPack_Builder*) setLoginMode:(int32_t) value {
  result.hasLoginMode = YES;
  result.loginMode = value;
  return self;
}
- (PP_LoginPack_Builder*) clearLoginMode {
  result.hasLoginMode = NO;
  result.loginMode = 0;
  return self;
}
- (BOOL) hasVersion {
  return result.hasVersion;
}
- (int32_t) version {
  return result.version;
}
- (PP_LoginPack_Builder*) setVersion:(int32_t) value {
  result.hasVersion = YES;
  result.version = value;
  return self;
}
- (PP_LoginPack_Builder*) clearVersion {
  result.hasVersion = NO;
  result.version = 0;
  return self;
}
- (BOOL) hasBagVersion {
  return result.hasBagVersion;
}
- (int32_t) bagVersion {
  return result.bagVersion;
}
- (PP_LoginPack_Builder*) setBagVersion:(int32_t) value {
  result.hasBagVersion = YES;
  result.bagVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearBagVersion {
  result.hasBagVersion = NO;
  result.bagVersion = 0;
  return self;
}
- (BOOL) hasRelationshipVersion {
  return result.hasRelationshipVersion;
}
- (int32_t) relationshipVersion {
  return result.relationshipVersion;
}
- (PP_LoginPack_Builder*) setRelationshipVersion:(int32_t) value {
  result.hasRelationshipVersion = YES;
  result.relationshipVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearRelationshipVersion {
  result.hasRelationshipVersion = NO;
  result.relationshipVersion = 0;
  return self;
}
- (BOOL) hasEquipVersion {
  return result.hasEquipVersion;
}
- (int32_t) equipVersion {
  return result.equipVersion;
}
- (PP_LoginPack_Builder*) setEquipVersion:(int32_t) value {
  result.hasEquipVersion = YES;
  result.equipVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearEquipVersion {
  result.hasEquipVersion = NO;
  result.equipVersion = 0;
  return self;
}
- (BOOL) hasPetVersion {
  return result.hasPetVersion;
}
- (int32_t) petVersion {
  return result.petVersion;
}
- (PP_LoginPack_Builder*) setPetVersion:(int32_t) value {
  result.hasPetVersion = YES;
  result.petVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearPetVersion {
  result.hasPetVersion = NO;
  result.petVersion = 0;
  return self;
}
- (BOOL) hasResVersion {
  return result.hasResVersion;
}
- (int32_t) resVersion {
  return result.resVersion;
}
- (PP_LoginPack_Builder*) setResVersion:(int32_t) value {
  result.hasResVersion = YES;
  result.resVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearResVersion {
  result.hasResVersion = NO;
  result.resVersion = 0;
  return self;
}
- (BOOL) hasFinishVersion {
  return result.hasFinishVersion;
}
- (int32_t) finishVersion {
  return result.finishVersion;
}
- (PP_LoginPack_Builder*) setFinishVersion:(int32_t) value {
  result.hasFinishVersion = YES;
  result.finishVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearFinishVersion {
  result.hasFinishVersion = NO;
  result.finishVersion = 0;
  return self;
}
- (BOOL) hasUnfinishVersion {
  return result.hasUnfinishVersion;
}
- (int32_t) unfinishVersion {
  return result.unfinishVersion;
}
- (PP_LoginPack_Builder*) setUnfinishVersion:(int32_t) value {
  result.hasUnfinishVersion = YES;
  result.unfinishVersion = value;
  return self;
}
- (PP_LoginPack_Builder*) clearUnfinishVersion {
  result.hasUnfinishVersion = NO;
  result.unfinishVersion = 0;
  return self;
}
- (BOOL) hasDuid {
  return result.hasDuid;
}
- (NSString*) duid {
  return result.duid;
}
- (PP_LoginPack_Builder*) setDuid:(NSString*) value {
  result.hasDuid = YES;
  result.duid = value;
  return self;
}
- (PP_LoginPack_Builder*) clearDuid {
  result.hasDuid = NO;
  result.duid = @"";
  return self;
}
@end

