// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_ChildSkillData.pb.h"

@class PP_ChildSkillData;
@class PP_ChildSkillData_Builder;
@class PP_LiveChildSkill;
@class PP_LiveChildSkill_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpLiveChildSkillRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_LiveChildSkill : PBGeneratedMessage {
@private
  BOOL hasSkillId_:1;
  BOOL hasLiveSkillId_:1;
  BOOL hasReqPractise_:1;
  BOOL hasReqLevel_:1;
  BOOL hasReqFormula_:1;
  BOOL hasTargetItemId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasSkillName_:1;
  BOOL hasSkillDes_:1;
  BOOL hasSkillIcon_:1;
  int32_t skillId;
  int32_t liveSkillId;
  int32_t reqPractise;
  int32_t reqLevel;
  int32_t reqFormula;
  int32_t targetItemId;
  int32_t createTime;
  NSString* skillName;
  NSString* skillDes;
  NSString* skillIcon;
  PBAppendableArray * skillDataArray;
}
- (BOOL) hasSkillId;
- (BOOL) hasLiveSkillId;
- (BOOL) hasSkillName;
- (BOOL) hasReqPractise;
- (BOOL) hasReqLevel;
- (BOOL) hasReqFormula;
- (BOOL) hasSkillDes;
- (BOOL) hasSkillIcon;
- (BOOL) hasTargetItemId;
- (BOOL) hasCreateTime;
@property (readonly) int32_t skillId;
@property (readonly) int32_t liveSkillId;
@property (readonly, retain) NSString* skillName;
@property (readonly) int32_t reqPractise;
@property (readonly) int32_t reqLevel;
@property (readonly) int32_t reqFormula;
@property (readonly, retain) NSString* skillDes;
@property (readonly, retain) NSString* skillIcon;
@property (readonly) int32_t targetItemId;
@property (readonly) int32_t createTime;
@property (readonly, retain) PBArray * skillData;
- (PP_ChildSkillData*)skillDataAtIndex:(NSUInteger)index;

+ (PP_LiveChildSkill*) defaultInstance;
- (PP_LiveChildSkill*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_LiveChildSkill_Builder*) builder;
+ (PP_LiveChildSkill_Builder*) builder;
+ (PP_LiveChildSkill_Builder*) builderWithPrototype:(PP_LiveChildSkill*) prototype;
- (PP_LiveChildSkill_Builder*) toBuilder;

+ (PP_LiveChildSkill*) parseFromData:(NSData*) data;
+ (PP_LiveChildSkill*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_LiveChildSkill*) parseFromInputStream:(NSInputStream*) input;
+ (PP_LiveChildSkill*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_LiveChildSkill*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_LiveChildSkill*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_LiveChildSkill_Builder : PBGeneratedMessage_Builder {
@private
  PP_LiveChildSkill* result;
}

- (PP_LiveChildSkill*) defaultInstance;

- (PP_LiveChildSkill_Builder*) clear;
- (PP_LiveChildSkill_Builder*) clone;

- (PP_LiveChildSkill*) build;
- (PP_LiveChildSkill*) buildPartial;

- (PP_LiveChildSkill_Builder*) mergeFrom:(PP_LiveChildSkill*) other;
- (PP_LiveChildSkill_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_LiveChildSkill_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSkillId;
- (int32_t) skillId;
- (PP_LiveChildSkill_Builder*) setSkillId:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearSkillId;

- (BOOL) hasLiveSkillId;
- (int32_t) liveSkillId;
- (PP_LiveChildSkill_Builder*) setLiveSkillId:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearLiveSkillId;

- (BOOL) hasSkillName;
- (NSString*) skillName;
- (PP_LiveChildSkill_Builder*) setSkillName:(NSString*) value;
- (PP_LiveChildSkill_Builder*) clearSkillName;

- (BOOL) hasReqPractise;
- (int32_t) reqPractise;
- (PP_LiveChildSkill_Builder*) setReqPractise:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearReqPractise;

- (BOOL) hasReqLevel;
- (int32_t) reqLevel;
- (PP_LiveChildSkill_Builder*) setReqLevel:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearReqLevel;

- (BOOL) hasReqFormula;
- (int32_t) reqFormula;
- (PP_LiveChildSkill_Builder*) setReqFormula:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearReqFormula;

- (BOOL) hasSkillDes;
- (NSString*) skillDes;
- (PP_LiveChildSkill_Builder*) setSkillDes:(NSString*) value;
- (PP_LiveChildSkill_Builder*) clearSkillDes;

- (BOOL) hasSkillIcon;
- (NSString*) skillIcon;
- (PP_LiveChildSkill_Builder*) setSkillIcon:(NSString*) value;
- (PP_LiveChildSkill_Builder*) clearSkillIcon;

- (BOOL) hasTargetItemId;
- (int32_t) targetItemId;
- (PP_LiveChildSkill_Builder*) setTargetItemId:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearTargetItemId;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_LiveChildSkill_Builder*) setCreateTime:(int32_t) value;
- (PP_LiveChildSkill_Builder*) clearCreateTime;

- (PBAppendableArray *)skillData;
- (PP_ChildSkillData*)skillDataAtIndex:(NSUInteger)index;
- (PP_LiveChildSkill_Builder *)addSkillData:(PP_ChildSkillData*)value;
- (PP_LiveChildSkill_Builder *)setSkillDataArray:(NSArray *)array;
- (PP_LiveChildSkill_Builder *)setSkillDataValues:(const PP_ChildSkillData* *)values count:(NSUInteger)count;
- (PP_LiveChildSkill_Builder *)clearSkillData;
@end

