// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_Message.pb.h"

@implementation PpMessageRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpMessageRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_Message ()
@property int32_t uid;
@property int32_t targetUid;
@property (retain) NSString* content;
@property int32_t createTime;
@end

@implementation PP_Message

- (BOOL) hasUid {
  return !!hasUid_;
}
- (void) setHasUid:(BOOL) value_ {
  hasUid_ = !!value_;
}
@synthesize uid;
- (BOOL) hasTargetUid {
  return !!hasTargetUid_;
}
- (void) setHasTargetUid:(BOOL) value_ {
  hasTargetUid_ = !!value_;
}
@synthesize targetUid;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value_ {
  hasContent_ = !!value_;
}
@synthesize content;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) value_ {
  hasCreateTime_ = !!value_;
}
@synthesize createTime;
- (void) dealloc {
  self.content = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.uid = 0;
    self.targetUid = 0;
    self.content = @"";
    self.createTime = 0;
  }
  return self;
}
static PP_Message* defaultPP_MessageInstance = nil;
+ (void) initialize {
  if (self == [PP_Message class]) {
    defaultPP_MessageInstance = [[PP_Message alloc] init];
  }
}
+ (PP_Message*) defaultInstance {
  return defaultPP_MessageInstance;
}
- (PP_Message*) defaultInstance {
  return defaultPP_MessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUid) {
    [output writeInt32:1 value:self.uid];
  }
  if (self.hasTargetUid) {
    [output writeInt32:2 value:self.targetUid];
  }
  if (self.hasContent) {
    [output writeString:3 value:self.content];
  }
  if (self.hasCreateTime) {
    [output writeInt32:4 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUid) {
    size_ += computeInt32Size(1, self.uid);
  }
  if (self.hasTargetUid) {
    size_ += computeInt32Size(2, self.targetUid);
  }
  if (self.hasContent) {
    size_ += computeStringSize(3, self.content);
  }
  if (self.hasCreateTime) {
    size_ += computeInt32Size(4, self.createTime);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_Message*) parseFromData:(NSData*) data {
  return (PP_Message*)[[[PP_Message builder] mergeFromData:data] build];
}
+ (PP_Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Message*)[[[PP_Message builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_Message*) parseFromInputStream:(NSInputStream*) input {
  return (PP_Message*)[[[PP_Message builder] mergeFromInputStream:input] build];
}
+ (PP_Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Message*)[[[PP_Message builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_Message*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_Message*)[[[PP_Message builder] mergeFromCodedInputStream:input] build];
}
+ (PP_Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_Message*)[[[PP_Message builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_Message_Builder*) builder {
  return [[[PP_Message_Builder alloc] init] autorelease];
}
+ (PP_Message_Builder*) builderWithPrototype:(PP_Message*) prototype {
  return [[PP_Message builder] mergeFrom:prototype];
}
- (PP_Message_Builder*) builder {
  return [PP_Message builder];
}
- (PP_Message_Builder*) toBuilder {
  return [PP_Message builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uid", [NSNumber numberWithInt:self.uid]];
  }
  if (self.hasTargetUid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"targetUid", [NSNumber numberWithInt:self.targetUid]];
  }
  if (self.hasContent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"content", self.content];
  }
  if (self.hasCreateTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createTime", [NSNumber numberWithInt:self.createTime]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_Message class]]) {
    return NO;
  }
  PP_Message *otherMessage = other;
  return
      self.hasUid == otherMessage.hasUid &&
      (!self.hasUid || self.uid == otherMessage.uid) &&
      self.hasTargetUid == otherMessage.hasTargetUid &&
      (!self.hasTargetUid || self.targetUid == otherMessage.targetUid) &&
      self.hasContent == otherMessage.hasContent &&
      (!self.hasContent || [self.content isEqual:otherMessage.content]) &&
      self.hasCreateTime == otherMessage.hasCreateTime &&
      (!self.hasCreateTime || self.createTime == otherMessage.createTime) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasUid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.uid] hash];
  }
  if (self.hasTargetUid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.targetUid] hash];
  }
  if (self.hasContent) {
    hashCode = hashCode * 31 + [self.content hash];
  }
  if (self.hasCreateTime) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.createTime] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_Message_Builder()
@property (retain) PP_Message* result;
@end

@implementation PP_Message_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_Message alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_Message_Builder*) clear {
  self.result = [[[PP_Message alloc] init] autorelease];
  return self;
}
- (PP_Message_Builder*) clone {
  return [PP_Message builderWithPrototype:result];
}
- (PP_Message*) defaultInstance {
  return [PP_Message defaultInstance];
}
- (PP_Message*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_Message*) buildPartial {
  PP_Message* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_Message_Builder*) mergeFrom:(PP_Message*) other {
  if (other == [PP_Message defaultInstance]) {
    return self;
  }
  if (other.hasUid) {
    [self setUid:other.uid];
  }
  if (other.hasTargetUid) {
    [self setTargetUid:other.targetUid];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUid:[input readInt32]];
        break;
      }
      case 16: {
        [self setTargetUid:[input readInt32]];
        break;
      }
      case 26: {
        [self setContent:[input readString]];
        break;
      }
      case 32: {
        [self setCreateTime:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasUid {
  return result.hasUid;
}
- (int32_t) uid {
  return result.uid;
}
- (PP_Message_Builder*) setUid:(int32_t) value {
  result.hasUid = YES;
  result.uid = value;
  return self;
}
- (PP_Message_Builder*) clearUid {
  result.hasUid = NO;
  result.uid = 0;
  return self;
}
- (BOOL) hasTargetUid {
  return result.hasTargetUid;
}
- (int32_t) targetUid {
  return result.targetUid;
}
- (PP_Message_Builder*) setTargetUid:(int32_t) value {
  result.hasTargetUid = YES;
  result.targetUid = value;
  return self;
}
- (PP_Message_Builder*) clearTargetUid {
  result.hasTargetUid = NO;
  result.targetUid = 0;
  return self;
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (PP_Message_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (PP_Message_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return result.hasCreateTime;
}
- (int32_t) createTime {
  return result.createTime;
}
- (PP_Message_Builder*) setCreateTime:(int32_t) value {
  result.hasCreateTime = YES;
  result.createTime = value;
  return self;
}
- (PP_Message_Builder*) clearCreateTime {
  result.hasCreateTime = NO;
  result.createTime = 0;
  return self;
}
@end

