// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Map;
@class PP_Map_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpMapRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Map : PBGeneratedMessage {
@private
  BOOL hasLtLongitude_:1;
  BOOL hasLtLatitude_:1;
  BOOL hasRbLongitude_:1;
  BOOL hasRbLatitude_:1;
  BOOL hasMapId_:1;
  BOOL hasMapNationId_:1;
  BOOL hasMapRealId_:1;
  BOOL hasPlayerNum_:1;
  BOOL hasUpdateTime_:1;
  BOOL hasMapName_:1;
  Float64 ltLongitude;
  Float64 ltLatitude;
  Float64 rbLongitude;
  Float64 rbLatitude;
  int32_t mapId;
  int32_t mapNationId;
  int32_t mapRealId;
  int32_t playerNum;
  int32_t updateTime;
  NSString* mapName;
}
- (BOOL) hasMapName;
- (BOOL) hasMapId;
- (BOOL) hasMapNationId;
- (BOOL) hasMapRealId;
- (BOOL) hasPlayerNum;
- (BOOL) hasLtLongitude;
- (BOOL) hasLtLatitude;
- (BOOL) hasRbLongitude;
- (BOOL) hasRbLatitude;
- (BOOL) hasUpdateTime;
@property (readonly, retain) NSString* mapName;
@property (readonly) int32_t mapId;
@property (readonly) int32_t mapNationId;
@property (readonly) int32_t mapRealId;
@property (readonly) int32_t playerNum;
@property (readonly) Float64 ltLongitude;
@property (readonly) Float64 ltLatitude;
@property (readonly) Float64 rbLongitude;
@property (readonly) Float64 rbLatitude;
@property (readonly) int32_t updateTime;

+ (PP_Map*) defaultInstance;
- (PP_Map*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Map_Builder*) builder;
+ (PP_Map_Builder*) builder;
+ (PP_Map_Builder*) builderWithPrototype:(PP_Map*) prototype;
- (PP_Map_Builder*) toBuilder;

+ (PP_Map*) parseFromData:(NSData*) data;
+ (PP_Map*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Map*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Map*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Map*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Map*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Map_Builder : PBGeneratedMessage_Builder {
@private
  PP_Map* result;
}

- (PP_Map*) defaultInstance;

- (PP_Map_Builder*) clear;
- (PP_Map_Builder*) clone;

- (PP_Map*) build;
- (PP_Map*) buildPartial;

- (PP_Map_Builder*) mergeFrom:(PP_Map*) other;
- (PP_Map_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Map_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMapName;
- (NSString*) mapName;
- (PP_Map_Builder*) setMapName:(NSString*) value;
- (PP_Map_Builder*) clearMapName;

- (BOOL) hasMapId;
- (int32_t) mapId;
- (PP_Map_Builder*) setMapId:(int32_t) value;
- (PP_Map_Builder*) clearMapId;

- (BOOL) hasMapNationId;
- (int32_t) mapNationId;
- (PP_Map_Builder*) setMapNationId:(int32_t) value;
- (PP_Map_Builder*) clearMapNationId;

- (BOOL) hasMapRealId;
- (int32_t) mapRealId;
- (PP_Map_Builder*) setMapRealId:(int32_t) value;
- (PP_Map_Builder*) clearMapRealId;

- (BOOL) hasPlayerNum;
- (int32_t) playerNum;
- (PP_Map_Builder*) setPlayerNum:(int32_t) value;
- (PP_Map_Builder*) clearPlayerNum;

- (BOOL) hasLtLongitude;
- (Float64) ltLongitude;
- (PP_Map_Builder*) setLtLongitude:(Float64) value;
- (PP_Map_Builder*) clearLtLongitude;

- (BOOL) hasLtLatitude;
- (Float64) ltLatitude;
- (PP_Map_Builder*) setLtLatitude:(Float64) value;
- (PP_Map_Builder*) clearLtLatitude;

- (BOOL) hasRbLongitude;
- (Float64) rbLongitude;
- (PP_Map_Builder*) setRbLongitude:(Float64) value;
- (PP_Map_Builder*) clearRbLongitude;

- (BOOL) hasRbLatitude;
- (Float64) rbLatitude;
- (PP_Map_Builder*) setRbLatitude:(Float64) value;
- (PP_Map_Builder*) clearRbLatitude;

- (BOOL) hasUpdateTime;
- (int32_t) updateTime;
- (PP_Map_Builder*) setUpdateTime:(int32_t) value;
- (PP_Map_Builder*) clearUpdateTime;
@end

