// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Message;
@class PP_Message_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Message : PBGeneratedMessage {
@private
  BOOL hasUid_:1;
  BOOL hasTargetUid_:1;
  BOOL hasCreateTime_:1;
  BOOL hasContent_:1;
  int32_t uid;
  int32_t targetUid;
  int32_t createTime;
  NSString* content;
}
- (BOOL) hasUid;
- (BOOL) hasTargetUid;
- (BOOL) hasContent;
- (BOOL) hasCreateTime;
@property (readonly) int32_t uid;
@property (readonly) int32_t targetUid;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t createTime;

+ (PP_Message*) defaultInstance;
- (PP_Message*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Message_Builder*) builder;
+ (PP_Message_Builder*) builder;
+ (PP_Message_Builder*) builderWithPrototype:(PP_Message*) prototype;
- (PP_Message_Builder*) toBuilder;

+ (PP_Message*) parseFromData:(NSData*) data;
+ (PP_Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Message*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Message_Builder : PBGeneratedMessage_Builder {
@private
  PP_Message* result;
}

- (PP_Message*) defaultInstance;

- (PP_Message_Builder*) clear;
- (PP_Message_Builder*) clone;

- (PP_Message*) build;
- (PP_Message*) buildPartial;

- (PP_Message_Builder*) mergeFrom:(PP_Message*) other;
- (PP_Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (int32_t) uid;
- (PP_Message_Builder*) setUid:(int32_t) value;
- (PP_Message_Builder*) clearUid;

- (BOOL) hasTargetUid;
- (int32_t) targetUid;
- (PP_Message_Builder*) setTargetUid:(int32_t) value;
- (PP_Message_Builder*) clearTargetUid;

- (BOOL) hasContent;
- (NSString*) content;
- (PP_Message_Builder*) setContent:(NSString*) value;
- (PP_Message_Builder*) clearContent;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_Message_Builder*) setCreateTime:(int32_t) value;
- (PP_Message_Builder*) clearCreateTime;
@end

