// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Pet_Equipment;
@class PP_Pet_Equipment_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpPetEquipmentRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Pet_Equipment : PBGeneratedMessage {
@private
  BOOL hasEquipId_:1;
  BOOL hasEquipLevel_:1;
  BOOL hasCreateTime_:1;
  int32_t equipId;
  int32_t equipLevel;
  int32_t createTime;
}
- (BOOL) hasEquipId;
- (BOOL) hasEquipLevel;
- (BOOL) hasCreateTime;
@property (readonly) int32_t equipId;
@property (readonly) int32_t equipLevel;
@property (readonly) int32_t createTime;

+ (PP_Pet_Equipment*) defaultInstance;
- (PP_Pet_Equipment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Pet_Equipment_Builder*) builder;
+ (PP_Pet_Equipment_Builder*) builder;
+ (PP_Pet_Equipment_Builder*) builderWithPrototype:(PP_Pet_Equipment*) prototype;
- (PP_Pet_Equipment_Builder*) toBuilder;

+ (PP_Pet_Equipment*) parseFromData:(NSData*) data;
+ (PP_Pet_Equipment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Pet_Equipment*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Pet_Equipment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Pet_Equipment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Pet_Equipment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Pet_Equipment_Builder : PBGeneratedMessage_Builder {
@private
  PP_Pet_Equipment* result;
}

- (PP_Pet_Equipment*) defaultInstance;

- (PP_Pet_Equipment_Builder*) clear;
- (PP_Pet_Equipment_Builder*) clone;

- (PP_Pet_Equipment*) build;
- (PP_Pet_Equipment*) buildPartial;

- (PP_Pet_Equipment_Builder*) mergeFrom:(PP_Pet_Equipment*) other;
- (PP_Pet_Equipment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Pet_Equipment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEquipId;
- (int32_t) equipId;
- (PP_Pet_Equipment_Builder*) setEquipId:(int32_t) value;
- (PP_Pet_Equipment_Builder*) clearEquipId;

- (BOOL) hasEquipLevel;
- (int32_t) equipLevel;
- (PP_Pet_Equipment_Builder*) setEquipLevel:(int32_t) value;
- (PP_Pet_Equipment_Builder*) clearEquipLevel;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_Pet_Equipment_Builder*) setCreateTime:(int32_t) value;
- (PP_Pet_Equipment_Builder*) clearCreateTime;
@end

