// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_Pet_Equipment.pb.h"
#import "PP_Pet_Skill.pb.h"

@class PP_Pet;
@class PP_Pet_Builder;
@class PP_Pet_Equipment;
@class PP_Pet_Equipment_Builder;
@class PP_Pet_Skill;
@class PP_Pet_Skill_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpPetRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Pet : PBGeneratedMessage {
@private
  BOOL hasAgile_:1;
  BOOL hasIntellegence_:1;
  BOOL hasVigour_:1;
  BOOL hasEndur_:1;
  BOOL hasAttack_:1;
  BOOL hasDefense_:1;
  BOOL hasMagicDamage_:1;
  BOOL hasMagicDefense_:1;
  BOOL hasTid_:1;
  BOOL hasAttackLevel_:1;
  BOOL hasDefenseLevel_:1;
  BOOL hasMagicLevel_:1;
  BOOL hasMagicDefenseLevel_:1;
  BOOL hasVersion_:1;
  BOOL hasMapId_:1;
  BOOL hasIsBoss_:1;
  BOOL hasIsNpc_:1;
  BOOL hasLastEquipVersionId_:1;
  BOOL hasLastSkillVersionId_:1;
  BOOL hasUid_:1;
  BOOL hasPetId_:1;
  BOOL hasPetElement_:1;
  BOOL hasLevel_:1;
  BOOL hasCurExp_:1;
  BOOL hasTotalExp_:1;
  BOOL hasCurHp_:1;
  BOOL hasTotalHp_:1;
  BOOL hasCurMp_:1;
  BOOL hasTotalMp_:1;
  BOOL hasState_:1;
  BOOL hasLife_:1;
  BOOL hasGrow_:1;
  BOOL hasFeel_:1;
  BOOL hasAge_:1;
  BOOL hasIsVariation_:1;
  BOOL hasVariationLevel_:1;
  BOOL hasPower_:1;
  BOOL hasPetName_:1;
  int32_t agile;
  int32_t intellegence;
  int32_t vigour;
  int32_t endur;
  int32_t attack;
  int32_t defense;
  int32_t magicDamage;
  int32_t magicDefense;
  int32_t tid;
  int32_t attackLevel;
  int32_t defenseLevel;
  int32_t magicLevel;
  int32_t magicDefenseLevel;
  int32_t version;
  int32_t mapId;
  int32_t isBoss;
  int32_t isNpc;
  int32_t lastEquipVersionId;
  int32_t lastSkillVersionId;
  int32_t uid;
  int32_t petId;
  int32_t petElement;
  int32_t level;
  int32_t curExp;
  int32_t totalExp;
  int32_t curHp;
  int32_t totalHp;
  int32_t curMp;
  int32_t totalMp;
  int32_t state;
  int32_t life;
  int32_t grow;
  int32_t feel;
  int32_t age;
  int32_t isVariation;
  int32_t variationLevel;
  int32_t power;
  NSString* petName;
  PBAppendableArray * equipmentsArray;
  PBAppendableArray * skillsArray;
}
- (BOOL) hasUid;
- (BOOL) hasPetId;
- (BOOL) hasPetName;
- (BOOL) hasPetElement;
- (BOOL) hasLevel;
- (BOOL) hasCurExp;
- (BOOL) hasTotalExp;
- (BOOL) hasCurHp;
- (BOOL) hasTotalHp;
- (BOOL) hasCurMp;
- (BOOL) hasTotalMp;
- (BOOL) hasState;
- (BOOL) hasLife;
- (BOOL) hasGrow;
- (BOOL) hasFeel;
- (BOOL) hasAge;
- (BOOL) hasIsVariation;
- (BOOL) hasVariationLevel;
- (BOOL) hasPower;
- (BOOL) hasAgile;
- (BOOL) hasIntellegence;
- (BOOL) hasVigour;
- (BOOL) hasEndur;
- (BOOL) hasAttack;
- (BOOL) hasDefense;
- (BOOL) hasMagicDamage;
- (BOOL) hasMagicDefense;
- (BOOL) hasTid;
- (BOOL) hasAttackLevel;
- (BOOL) hasDefenseLevel;
- (BOOL) hasMagicLevel;
- (BOOL) hasMagicDefenseLevel;
- (BOOL) hasVersion;
- (BOOL) hasMapId;
- (BOOL) hasIsBoss;
- (BOOL) hasIsNpc;
- (BOOL) hasLastEquipVersionId;
- (BOOL) hasLastSkillVersionId;
@property (readonly) int32_t uid;
@property (readonly) int32_t petId;
@property (readonly, retain) NSString* petName;
@property (readonly) int32_t petElement;
@property (readonly) int32_t level;
@property (readonly) int32_t curExp;
@property (readonly) int32_t totalExp;
@property (readonly) int32_t curHp;
@property (readonly) int32_t totalHp;
@property (readonly) int32_t curMp;
@property (readonly) int32_t totalMp;
@property (readonly) int32_t state;
@property (readonly) int32_t life;
@property (readonly) int32_t grow;
@property (readonly) int32_t feel;
@property (readonly) int32_t age;
@property (readonly) int32_t isVariation;
@property (readonly) int32_t variationLevel;
@property (readonly) int32_t power;
@property (readonly) int32_t agile;
@property (readonly) int32_t intellegence;
@property (readonly) int32_t vigour;
@property (readonly) int32_t endur;
@property (readonly) int32_t attack;
@property (readonly) int32_t defense;
@property (readonly) int32_t magicDamage;
@property (readonly) int32_t magicDefense;
@property (readonly) int32_t tid;
@property (readonly) int32_t attackLevel;
@property (readonly) int32_t defenseLevel;
@property (readonly) int32_t magicLevel;
@property (readonly) int32_t magicDefenseLevel;
@property (readonly) int32_t version;
@property (readonly) int32_t mapId;
@property (readonly) int32_t isBoss;
@property (readonly) int32_t isNpc;
@property (readonly) int32_t lastEquipVersionId;
@property (readonly) int32_t lastSkillVersionId;
@property (readonly, retain) PBArray * equipments;
@property (readonly, retain) PBArray * skills;
- (PP_Pet_Equipment*)equipmentsAtIndex:(NSUInteger)index;
- (PP_Pet_Skill*)skillsAtIndex:(NSUInteger)index;

+ (PP_Pet*) defaultInstance;
- (PP_Pet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Pet_Builder*) builder;
+ (PP_Pet_Builder*) builder;
+ (PP_Pet_Builder*) builderWithPrototype:(PP_Pet*) prototype;
- (PP_Pet_Builder*) toBuilder;

+ (PP_Pet*) parseFromData:(NSData*) data;
+ (PP_Pet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Pet*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Pet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Pet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Pet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Pet_Builder : PBGeneratedMessage_Builder {
@private
  PP_Pet* result;
}

- (PP_Pet*) defaultInstance;

- (PP_Pet_Builder*) clear;
- (PP_Pet_Builder*) clone;

- (PP_Pet*) build;
- (PP_Pet*) buildPartial;

- (PP_Pet_Builder*) mergeFrom:(PP_Pet*) other;
- (PP_Pet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Pet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (int32_t) uid;
- (PP_Pet_Builder*) setUid:(int32_t) value;
- (PP_Pet_Builder*) clearUid;

- (BOOL) hasPetId;
- (int32_t) petId;
- (PP_Pet_Builder*) setPetId:(int32_t) value;
- (PP_Pet_Builder*) clearPetId;

- (BOOL) hasPetName;
- (NSString*) petName;
- (PP_Pet_Builder*) setPetName:(NSString*) value;
- (PP_Pet_Builder*) clearPetName;

- (BOOL) hasPetElement;
- (int32_t) petElement;
- (PP_Pet_Builder*) setPetElement:(int32_t) value;
- (PP_Pet_Builder*) clearPetElement;

- (BOOL) hasLevel;
- (int32_t) level;
- (PP_Pet_Builder*) setLevel:(int32_t) value;
- (PP_Pet_Builder*) clearLevel;

- (BOOL) hasCurExp;
- (int32_t) curExp;
- (PP_Pet_Builder*) setCurExp:(int32_t) value;
- (PP_Pet_Builder*) clearCurExp;

- (BOOL) hasTotalExp;
- (int32_t) totalExp;
- (PP_Pet_Builder*) setTotalExp:(int32_t) value;
- (PP_Pet_Builder*) clearTotalExp;

- (BOOL) hasCurHp;
- (int32_t) curHp;
- (PP_Pet_Builder*) setCurHp:(int32_t) value;
- (PP_Pet_Builder*) clearCurHp;

- (BOOL) hasTotalHp;
- (int32_t) totalHp;
- (PP_Pet_Builder*) setTotalHp:(int32_t) value;
- (PP_Pet_Builder*) clearTotalHp;

- (BOOL) hasCurMp;
- (int32_t) curMp;
- (PP_Pet_Builder*) setCurMp:(int32_t) value;
- (PP_Pet_Builder*) clearCurMp;

- (BOOL) hasTotalMp;
- (int32_t) totalMp;
- (PP_Pet_Builder*) setTotalMp:(int32_t) value;
- (PP_Pet_Builder*) clearTotalMp;

- (BOOL) hasState;
- (int32_t) state;
- (PP_Pet_Builder*) setState:(int32_t) value;
- (PP_Pet_Builder*) clearState;

- (BOOL) hasLife;
- (int32_t) life;
- (PP_Pet_Builder*) setLife:(int32_t) value;
- (PP_Pet_Builder*) clearLife;

- (BOOL) hasGrow;
- (int32_t) grow;
- (PP_Pet_Builder*) setGrow:(int32_t) value;
- (PP_Pet_Builder*) clearGrow;

- (BOOL) hasFeel;
- (int32_t) feel;
- (PP_Pet_Builder*) setFeel:(int32_t) value;
- (PP_Pet_Builder*) clearFeel;

- (BOOL) hasAge;
- (int32_t) age;
- (PP_Pet_Builder*) setAge:(int32_t) value;
- (PP_Pet_Builder*) clearAge;

- (BOOL) hasIsVariation;
- (int32_t) isVariation;
- (PP_Pet_Builder*) setIsVariation:(int32_t) value;
- (PP_Pet_Builder*) clearIsVariation;

- (BOOL) hasVariationLevel;
- (int32_t) variationLevel;
- (PP_Pet_Builder*) setVariationLevel:(int32_t) value;
- (PP_Pet_Builder*) clearVariationLevel;

- (BOOL) hasPower;
- (int32_t) power;
- (PP_Pet_Builder*) setPower:(int32_t) value;
- (PP_Pet_Builder*) clearPower;

- (BOOL) hasAgile;
- (int32_t) agile;
- (PP_Pet_Builder*) setAgile:(int32_t) value;
- (PP_Pet_Builder*) clearAgile;

- (BOOL) hasIntellegence;
- (int32_t) intellegence;
- (PP_Pet_Builder*) setIntellegence:(int32_t) value;
- (PP_Pet_Builder*) clearIntellegence;

- (BOOL) hasVigour;
- (int32_t) vigour;
- (PP_Pet_Builder*) setVigour:(int32_t) value;
- (PP_Pet_Builder*) clearVigour;

- (BOOL) hasEndur;
- (int32_t) endur;
- (PP_Pet_Builder*) setEndur:(int32_t) value;
- (PP_Pet_Builder*) clearEndur;

- (BOOL) hasAttack;
- (int32_t) attack;
- (PP_Pet_Builder*) setAttack:(int32_t) value;
- (PP_Pet_Builder*) clearAttack;

- (BOOL) hasDefense;
- (int32_t) defense;
- (PP_Pet_Builder*) setDefense:(int32_t) value;
- (PP_Pet_Builder*) clearDefense;

- (BOOL) hasMagicDamage;
- (int32_t) magicDamage;
- (PP_Pet_Builder*) setMagicDamage:(int32_t) value;
- (PP_Pet_Builder*) clearMagicDamage;

- (BOOL) hasMagicDefense;
- (int32_t) magicDefense;
- (PP_Pet_Builder*) setMagicDefense:(int32_t) value;
- (PP_Pet_Builder*) clearMagicDefense;

- (BOOL) hasTid;
- (int32_t) tid;
- (PP_Pet_Builder*) setTid:(int32_t) value;
- (PP_Pet_Builder*) clearTid;

- (BOOL) hasAttackLevel;
- (int32_t) attackLevel;
- (PP_Pet_Builder*) setAttackLevel:(int32_t) value;
- (PP_Pet_Builder*) clearAttackLevel;

- (BOOL) hasDefenseLevel;
- (int32_t) defenseLevel;
- (PP_Pet_Builder*) setDefenseLevel:(int32_t) value;
- (PP_Pet_Builder*) clearDefenseLevel;

- (BOOL) hasMagicLevel;
- (int32_t) magicLevel;
- (PP_Pet_Builder*) setMagicLevel:(int32_t) value;
- (PP_Pet_Builder*) clearMagicLevel;

- (BOOL) hasMagicDefenseLevel;
- (int32_t) magicDefenseLevel;
- (PP_Pet_Builder*) setMagicDefenseLevel:(int32_t) value;
- (PP_Pet_Builder*) clearMagicDefenseLevel;

- (BOOL) hasVersion;
- (int32_t) version;
- (PP_Pet_Builder*) setVersion:(int32_t) value;
- (PP_Pet_Builder*) clearVersion;

- (BOOL) hasMapId;
- (int32_t) mapId;
- (PP_Pet_Builder*) setMapId:(int32_t) value;
- (PP_Pet_Builder*) clearMapId;

- (BOOL) hasIsBoss;
- (int32_t) isBoss;
- (PP_Pet_Builder*) setIsBoss:(int32_t) value;
- (PP_Pet_Builder*) clearIsBoss;

- (BOOL) hasIsNpc;
- (int32_t) isNpc;
- (PP_Pet_Builder*) setIsNpc:(int32_t) value;
- (PP_Pet_Builder*) clearIsNpc;

- (BOOL) hasLastEquipVersionId;
- (int32_t) lastEquipVersionId;
- (PP_Pet_Builder*) setLastEquipVersionId:(int32_t) value;
- (PP_Pet_Builder*) clearLastEquipVersionId;

- (BOOL) hasLastSkillVersionId;
- (int32_t) lastSkillVersionId;
- (PP_Pet_Builder*) setLastSkillVersionId:(int32_t) value;
- (PP_Pet_Builder*) clearLastSkillVersionId;

- (PBAppendableArray *)equipments;
- (PP_Pet_Equipment*)equipmentsAtIndex:(NSUInteger)index;
- (PP_Pet_Builder *)addEquipments:(PP_Pet_Equipment*)value;
- (PP_Pet_Builder *)setEquipmentsArray:(NSArray *)array;
- (PP_Pet_Builder *)setEquipmentsValues:(const PP_Pet_Equipment* *)values count:(NSUInteger)count;
- (PP_Pet_Builder *)clearEquipments;

- (PBAppendableArray *)skills;
- (PP_Pet_Skill*)skillsAtIndex:(NSUInteger)index;
- (PP_Pet_Builder *)addSkills:(PP_Pet_Skill*)value;
- (PP_Pet_Builder *)setSkillsArray:(NSArray *)array;
- (PP_Pet_Builder *)setSkillsValues:(const PP_Pet_Skill* *)values count:(NSUInteger)count;
- (PP_Pet_Builder *)clearSkills;
@end

