// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_ResPointData.pb.h"

@implementation PpResPointDataRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpResPointDataRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_ResPointData ()
@property int32_t monsterId;
@property int32_t monsterNum;
@end

@implementation PP_ResPointData

- (BOOL) hasMonsterId {
  return !!hasMonsterId_;
}
- (void) setHasMonsterId:(BOOL) value_ {
  hasMonsterId_ = !!value_;
}
@synthesize monsterId;
- (BOOL) hasMonsterNum {
  return !!hasMonsterNum_;
}
- (void) setHasMonsterNum:(BOOL) value_ {
  hasMonsterNum_ = !!value_;
}
@synthesize monsterNum;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.monsterId = 0;
    self.monsterNum = 0;
  }
  return self;
}
static PP_ResPointData* defaultPP_ResPointDataInstance = nil;
+ (void) initialize {
  if (self == [PP_ResPointData class]) {
    defaultPP_ResPointDataInstance = [[PP_ResPointData alloc] init];
  }
}
+ (PP_ResPointData*) defaultInstance {
  return defaultPP_ResPointDataInstance;
}
- (PP_ResPointData*) defaultInstance {
  return defaultPP_ResPointDataInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMonsterId) {
    [output writeInt32:1 value:self.monsterId];
  }
  if (self.hasMonsterNum) {
    [output writeInt32:2 value:self.monsterNum];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasMonsterId) {
    size_ += computeInt32Size(1, self.monsterId);
  }
  if (self.hasMonsterNum) {
    size_ += computeInt32Size(2, self.monsterNum);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_ResPointData*) parseFromData:(NSData*) data {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromData:data] build];
}
+ (PP_ResPointData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_ResPointData*) parseFromInputStream:(NSInputStream*) input {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromInputStream:input] build];
}
+ (PP_ResPointData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ResPointData*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromCodedInputStream:input] build];
}
+ (PP_ResPointData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_ResPointData*)[[[PP_ResPointData builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_ResPointData_Builder*) builder {
  return [[[PP_ResPointData_Builder alloc] init] autorelease];
}
+ (PP_ResPointData_Builder*) builderWithPrototype:(PP_ResPointData*) prototype {
  return [[PP_ResPointData builder] mergeFrom:prototype];
}
- (PP_ResPointData_Builder*) builder {
  return [PP_ResPointData builder];
}
- (PP_ResPointData_Builder*) toBuilder {
  return [PP_ResPointData builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasMonsterId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"monsterId", [NSNumber numberWithInt:self.monsterId]];
  }
  if (self.hasMonsterNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"monsterNum", [NSNumber numberWithInt:self.monsterNum]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_ResPointData class]]) {
    return NO;
  }
  PP_ResPointData *otherMessage = other;
  return
      self.hasMonsterId == otherMessage.hasMonsterId &&
      (!self.hasMonsterId || self.monsterId == otherMessage.monsterId) &&
      self.hasMonsterNum == otherMessage.hasMonsterNum &&
      (!self.hasMonsterNum || self.monsterNum == otherMessage.monsterNum) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasMonsterId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.monsterId] hash];
  }
  if (self.hasMonsterNum) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.monsterNum] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_ResPointData_Builder()
@property (retain) PP_ResPointData* result;
@end

@implementation PP_ResPointData_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_ResPointData alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_ResPointData_Builder*) clear {
  self.result = [[[PP_ResPointData alloc] init] autorelease];
  return self;
}
- (PP_ResPointData_Builder*) clone {
  return [PP_ResPointData builderWithPrototype:result];
}
- (PP_ResPointData*) defaultInstance {
  return [PP_ResPointData defaultInstance];
}
- (PP_ResPointData*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_ResPointData*) buildPartial {
  PP_ResPointData* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_ResPointData_Builder*) mergeFrom:(PP_ResPointData*) other {
  if (other == [PP_ResPointData defaultInstance]) {
    return self;
  }
  if (other.hasMonsterId) {
    [self setMonsterId:other.monsterId];
  }
  if (other.hasMonsterNum) {
    [self setMonsterNum:other.monsterNum];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_ResPointData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_ResPointData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setMonsterId:[input readInt32]];
        break;
      }
      case 16: {
        [self setMonsterNum:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasMonsterId {
  return result.hasMonsterId;
}
- (int32_t) monsterId {
  return result.monsterId;
}
- (PP_ResPointData_Builder*) setMonsterId:(int32_t) value {
  result.hasMonsterId = YES;
  result.monsterId = value;
  return self;
}
- (PP_ResPointData_Builder*) clearMonsterId {
  result.hasMonsterId = NO;
  result.monsterId = 0;
  return self;
}
- (BOOL) hasMonsterNum {
  return result.hasMonsterNum;
}
- (int32_t) monsterNum {
  return result.monsterNum;
}
- (PP_ResPointData_Builder*) setMonsterNum:(int32_t) value {
  result.hasMonsterNum = YES;
  result.monsterNum = value;
  return self;
}
- (PP_ResPointData_Builder*) clearMonsterNum {
  result.hasMonsterNum = NO;
  result.monsterNum = 0;
  return self;
}
@end

