// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_ResPointData;
@class PP_ResPointData_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpResPointDataRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_ResPointData : PBGeneratedMessage {
@private
  BOOL hasMonsterId_:1;
  BOOL hasMonsterNum_:1;
  int32_t monsterId;
  int32_t monsterNum;
}
- (BOOL) hasMonsterId;
- (BOOL) hasMonsterNum;
@property (readonly) int32_t monsterId;
@property (readonly) int32_t monsterNum;

+ (PP_ResPointData*) defaultInstance;
- (PP_ResPointData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_ResPointData_Builder*) builder;
+ (PP_ResPointData_Builder*) builder;
+ (PP_ResPointData_Builder*) builderWithPrototype:(PP_ResPointData*) prototype;
- (PP_ResPointData_Builder*) toBuilder;

+ (PP_ResPointData*) parseFromData:(NSData*) data;
+ (PP_ResPointData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ResPointData*) parseFromInputStream:(NSInputStream*) input;
+ (PP_ResPointData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_ResPointData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_ResPointData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_ResPointData_Builder : PBGeneratedMessage_Builder {
@private
  PP_ResPointData* result;
}

- (PP_ResPointData*) defaultInstance;

- (PP_ResPointData_Builder*) clear;
- (PP_ResPointData_Builder*) clone;

- (PP_ResPointData*) build;
- (PP_ResPointData*) buildPartial;

- (PP_ResPointData_Builder*) mergeFrom:(PP_ResPointData*) other;
- (PP_ResPointData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_ResPointData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMonsterId;
- (int32_t) monsterId;
- (PP_ResPointData_Builder*) setMonsterId:(int32_t) value;
- (PP_ResPointData_Builder*) clearMonsterId;

- (BOOL) hasMonsterNum;
- (int32_t) monsterNum;
- (PP_ResPointData_Builder*) setMonsterNum:(int32_t) value;
- (PP_ResPointData_Builder*) clearMonsterNum;
@end

