// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Test;
@class PP_Test_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpTestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Test : PBGeneratedMessage {
@private
  BOOL hasAge_:1;
  BOOL hasName_:1;
  int32_t age;
  NSString* name;
}
- (BOOL) hasAge;
- (BOOL) hasName;
@property (readonly) int32_t age;
@property (readonly, retain) NSString* name;

+ (PP_Test*) defaultInstance;
- (PP_Test*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Test_Builder*) builder;
+ (PP_Test_Builder*) builder;
+ (PP_Test_Builder*) builderWithPrototype:(PP_Test*) prototype;
- (PP_Test_Builder*) toBuilder;

+ (PP_Test*) parseFromData:(NSData*) data;
+ (PP_Test*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Test*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Test*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Test*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Test*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Test_Builder : PBGeneratedMessage_Builder {
@private
  PP_Test* result;
}

- (PP_Test*) defaultInstance;

- (PP_Test_Builder*) clear;
- (PP_Test_Builder*) clone;

- (PP_Test*) build;
- (PP_Test*) buildPartial;

- (PP_Test_Builder*) mergeFrom:(PP_Test*) other;
- (PP_Test_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Test_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAge;
- (int32_t) age;
- (PP_Test_Builder*) setAge:(int32_t) value;
- (PP_Test_Builder*) clearAge;

- (BOOL) hasName;
- (NSString*) name;
- (PP_Test_Builder*) setName:(NSString*) value;
- (PP_Test_Builder*) clearName;
@end

