// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_Task_Award;
@class PP_Task_Award_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpTaskAwardRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_Task_Award : PBGeneratedMessage {
@private
  BOOL hasAwardType_:1;
  BOOL hasItemId_:1;
  BOOL hasAwardNum_:1;
  int32_t awardType;
  int32_t itemId;
  int32_t awardNum;
}
- (BOOL) hasAwardType;
- (BOOL) hasItemId;
- (BOOL) hasAwardNum;
@property (readonly) int32_t awardType;
@property (readonly) int32_t itemId;
@property (readonly) int32_t awardNum;

+ (PP_Task_Award*) defaultInstance;
- (PP_Task_Award*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_Task_Award_Builder*) builder;
+ (PP_Task_Award_Builder*) builder;
+ (PP_Task_Award_Builder*) builderWithPrototype:(PP_Task_Award*) prototype;
- (PP_Task_Award_Builder*) toBuilder;

+ (PP_Task_Award*) parseFromData:(NSData*) data;
+ (PP_Task_Award*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Task_Award*) parseFromInputStream:(NSInputStream*) input;
+ (PP_Task_Award*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_Task_Award*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_Task_Award*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_Task_Award_Builder : PBGeneratedMessage_Builder {
@private
  PP_Task_Award* result;
}

- (PP_Task_Award*) defaultInstance;

- (PP_Task_Award_Builder*) clear;
- (PP_Task_Award_Builder*) clone;

- (PP_Task_Award*) build;
- (PP_Task_Award*) buildPartial;

- (PP_Task_Award_Builder*) mergeFrom:(PP_Task_Award*) other;
- (PP_Task_Award_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_Task_Award_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAwardType;
- (int32_t) awardType;
- (PP_Task_Award_Builder*) setAwardType:(int32_t) value;
- (PP_Task_Award_Builder*) clearAwardType;

- (BOOL) hasItemId;
- (int32_t) itemId;
- (PP_Task_Award_Builder*) setItemId:(int32_t) value;
- (PP_Task_Award_Builder*) clearItemId;

- (BOOL) hasAwardNum;
- (int32_t) awardNum;
- (PP_Task_Award_Builder*) setAwardNum:(int32_t) value;
- (PP_Task_Award_Builder*) clearAwardNum;
@end

