// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_ResourcePoint.pb.h"

@class PP_ResPointData;
@class PP_ResPointData_Builder;
@class PP_ResourcePoint;
@class PP_ResourcePoint_Builder;
@class PP_UserResPoint;
@class PP_UserResPoint_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpUserResPointRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_UserResPoint : PBGeneratedMessage {
@private
  BOOL hasUid_:1;
  BOOL hasVersionId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasResPoint_:1;
  int32_t uid;
  int32_t versionId;
  int32_t createTime;
  PP_ResourcePoint* resPoint;
}
- (BOOL) hasUid;
- (BOOL) hasResPoint;
- (BOOL) hasVersionId;
- (BOOL) hasCreateTime;
@property (readonly) int32_t uid;
@property (readonly, retain) PP_ResourcePoint* resPoint;
@property (readonly) int32_t versionId;
@property (readonly) int32_t createTime;

+ (PP_UserResPoint*) defaultInstance;
- (PP_UserResPoint*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_UserResPoint_Builder*) builder;
+ (PP_UserResPoint_Builder*) builder;
+ (PP_UserResPoint_Builder*) builderWithPrototype:(PP_UserResPoint*) prototype;
- (PP_UserResPoint_Builder*) toBuilder;

+ (PP_UserResPoint*) parseFromData:(NSData*) data;
+ (PP_UserResPoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_UserResPoint*) parseFromInputStream:(NSInputStream*) input;
+ (PP_UserResPoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_UserResPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_UserResPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_UserResPoint_Builder : PBGeneratedMessage_Builder {
@private
  PP_UserResPoint* result;
}

- (PP_UserResPoint*) defaultInstance;

- (PP_UserResPoint_Builder*) clear;
- (PP_UserResPoint_Builder*) clone;

- (PP_UserResPoint*) build;
- (PP_UserResPoint*) buildPartial;

- (PP_UserResPoint_Builder*) mergeFrom:(PP_UserResPoint*) other;
- (PP_UserResPoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_UserResPoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (int32_t) uid;
- (PP_UserResPoint_Builder*) setUid:(int32_t) value;
- (PP_UserResPoint_Builder*) clearUid;

- (BOOL) hasResPoint;
- (PP_ResourcePoint*) resPoint;
- (PP_UserResPoint_Builder*) setResPoint:(PP_ResourcePoint*) value;
- (PP_UserResPoint_Builder*) setResPointBuilder:(PP_ResourcePoint_Builder*) builderForValue;
- (PP_UserResPoint_Builder*) mergeResPoint:(PP_ResourcePoint*) value;
- (PP_UserResPoint_Builder*) clearResPoint;

- (BOOL) hasVersionId;
- (int32_t) versionId;
- (PP_UserResPoint_Builder*) setVersionId:(int32_t) value;
- (PP_UserResPoint_Builder*) clearVersionId;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_UserResPoint_Builder*) setCreateTime:(int32_t) value;
- (PP_UserResPoint_Builder*) clearCreateTime;
@end

