// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_AccTime;
@class PP_AccTime_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpAccTimeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_AccTime : PBGeneratedMessage {
@private
  BOOL hasCreateTime_:1;
  BOOL hasLastLogin_:1;
  int32_t createTime;
  int32_t lastLogin;
}
- (BOOL) hasCreateTime;
- (BOOL) hasLastLogin;
@property (readonly) int32_t createTime;
@property (readonly) int32_t lastLogin;

+ (PP_AccTime*) defaultInstance;
- (PP_AccTime*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_AccTime_Builder*) builder;
+ (PP_AccTime_Builder*) builder;
+ (PP_AccTime_Builder*) builderWithPrototype:(PP_AccTime*) prototype;
- (PP_AccTime_Builder*) toBuilder;

+ (PP_AccTime*) parseFromData:(NSData*) data;
+ (PP_AccTime*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_AccTime*) parseFromInputStream:(NSInputStream*) input;
+ (PP_AccTime*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_AccTime*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_AccTime*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_AccTime_Builder : PBGeneratedMessage_Builder {
@private
  PP_AccTime* result;
}

- (PP_AccTime*) defaultInstance;

- (PP_AccTime_Builder*) clear;
- (PP_AccTime_Builder*) clone;

- (PP_AccTime*) build;
- (PP_AccTime*) buildPartial;

- (PP_AccTime_Builder*) mergeFrom:(PP_AccTime*) other;
- (PP_AccTime_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_AccTime_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (PP_AccTime_Builder*) setCreateTime:(int32_t) value;
- (PP_AccTime_Builder*) clearCreateTime;

- (BOOL) hasLastLogin;
- (int32_t) lastLogin;
- (PP_AccTime_Builder*) setLastLogin:(int32_t) value;
- (PP_AccTime_Builder*) clearLastLogin;
@end

