// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_CLUser.pb.h"
#import "PP_BattlePet.pb.h"

@class PP_AccTime;
@class PP_AccTime_Builder;
@class PP_BattleInfo;
@class PP_BattleInfo_Builder;
@class PP_BattlePet;
@class PP_BattlePet_Builder;
@class PP_CLUser;
@class PP_CLUser_Builder;
@class PP_Location;
@class PP_Location_Builder;
@class PP_Pet;
@class PP_Pet_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpBattleInfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_BattleInfo : PBGeneratedMessage {
@private
  BOOL hasBattleType_:1;
  BOOL hasTargetUser_:1;
  int32_t battleType;
  PP_CLUser* targetUser;
  PBAppendableArray * autoPetsArray;
}
- (BOOL) hasBattleType;
- (BOOL) hasTargetUser;
@property (readonly) int32_t battleType;
@property (readonly, retain) PP_CLUser* targetUser;
@property (readonly, retain) PBArray * autoPets;
- (PP_BattlePet*)autoPetsAtIndex:(NSUInteger)index;

+ (PP_BattleInfo*) defaultInstance;
- (PP_BattleInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_BattleInfo_Builder*) builder;
+ (PP_BattleInfo_Builder*) builder;
+ (PP_BattleInfo_Builder*) builderWithPrototype:(PP_BattleInfo*) prototype;
- (PP_BattleInfo_Builder*) toBuilder;

+ (PP_BattleInfo*) parseFromData:(NSData*) data;
+ (PP_BattleInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_BattleInfo*) parseFromInputStream:(NSInputStream*) input;
+ (PP_BattleInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_BattleInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_BattleInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_BattleInfo_Builder : PBGeneratedMessage_Builder {
@private
  PP_BattleInfo* result;
}

- (PP_BattleInfo*) defaultInstance;

- (PP_BattleInfo_Builder*) clear;
- (PP_BattleInfo_Builder*) clone;

- (PP_BattleInfo*) build;
- (PP_BattleInfo*) buildPartial;

- (PP_BattleInfo_Builder*) mergeFrom:(PP_BattleInfo*) other;
- (PP_BattleInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_BattleInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBattleType;
- (int32_t) battleType;
- (PP_BattleInfo_Builder*) setBattleType:(int32_t) value;
- (PP_BattleInfo_Builder*) clearBattleType;

- (BOOL) hasTargetUser;
- (PP_CLUser*) targetUser;
- (PP_BattleInfo_Builder*) setTargetUser:(PP_CLUser*) value;
- (PP_BattleInfo_Builder*) setTargetUserBuilder:(PP_CLUser_Builder*) builderForValue;
- (PP_BattleInfo_Builder*) mergeTargetUser:(PP_CLUser*) value;
- (PP_BattleInfo_Builder*) clearTargetUser;

- (PBAppendableArray *)autoPets;
- (PP_BattlePet*)autoPetsAtIndex:(NSUInteger)index;
- (PP_BattleInfo_Builder *)addAutoPets:(PP_BattlePet*)value;
- (PP_BattleInfo_Builder *)setAutoPetsArray:(NSArray *)array;
- (PP_BattleInfo_Builder *)setAutoPetsValues:(const PP_BattlePet* *)values count:(NSUInteger)count;
- (PP_BattleInfo_Builder *)clearAutoPets;
@end

