// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PP_BattlePet;
@class PP_BattlePet_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpBattlePetRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_BattlePet : PBGeneratedMessage {
@private
  BOOL hasTid_:1;
  BOOL hasMid_:1;
  BOOL hasLevel_:1;
  BOOL hasIsVariation_:1;
  BOOL hasVariationLevel_:1;
  int32_t tid;
  int32_t mid;
  int32_t level;
  int32_t isVariation;
  int32_t variationLevel;
}
- (BOOL) hasTid;
- (BOOL) hasMid;
- (BOOL) hasLevel;
- (BOOL) hasIsVariation;
- (BOOL) hasVariationLevel;
@property (readonly) int32_t tid;
@property (readonly) int32_t mid;
@property (readonly) int32_t level;
@property (readonly) int32_t isVariation;
@property (readonly) int32_t variationLevel;

+ (PP_BattlePet*) defaultInstance;
- (PP_BattlePet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_BattlePet_Builder*) builder;
+ (PP_BattlePet_Builder*) builder;
+ (PP_BattlePet_Builder*) builderWithPrototype:(PP_BattlePet*) prototype;
- (PP_BattlePet_Builder*) toBuilder;

+ (PP_BattlePet*) parseFromData:(NSData*) data;
+ (PP_BattlePet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_BattlePet*) parseFromInputStream:(NSInputStream*) input;
+ (PP_BattlePet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_BattlePet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_BattlePet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_BattlePet_Builder : PBGeneratedMessage_Builder {
@private
  PP_BattlePet* result;
}

- (PP_BattlePet*) defaultInstance;

- (PP_BattlePet_Builder*) clear;
- (PP_BattlePet_Builder*) clone;

- (PP_BattlePet*) build;
- (PP_BattlePet*) buildPartial;

- (PP_BattlePet_Builder*) mergeFrom:(PP_BattlePet*) other;
- (PP_BattlePet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_BattlePet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTid;
- (int32_t) tid;
- (PP_BattlePet_Builder*) setTid:(int32_t) value;
- (PP_BattlePet_Builder*) clearTid;

- (BOOL) hasMid;
- (int32_t) mid;
- (PP_BattlePet_Builder*) setMid:(int32_t) value;
- (PP_BattlePet_Builder*) clearMid;

- (BOOL) hasLevel;
- (int32_t) level;
- (PP_BattlePet_Builder*) setLevel:(int32_t) value;
- (PP_BattlePet_Builder*) clearLevel;

- (BOOL) hasIsVariation;
- (int32_t) isVariation;
- (PP_BattlePet_Builder*) setIsVariation:(int32_t) value;
- (PP_BattlePet_Builder*) clearIsVariation;

- (BOOL) hasVariationLevel;
- (int32_t) variationLevel;
- (PP_BattlePet_Builder*) setVariationLevel:(int32_t) value;
- (PP_BattlePet_Builder*) clearVariationLevel;
@end

