// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "PP_Account.pb.h"

@class PP_Account;
@class PP_Account_Builder;
@class PP_LoginPack;
@class PP_LoginPack_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface PpLoginPackRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PP_LoginPack : PBGeneratedMessage {
@private
  BOOL hasLoginMode_:1;
  BOOL hasVersion_:1;
  BOOL hasAccount_:1;
  int32_t loginMode;
  int32_t version;
  PP_Account* account;
}
- (BOOL) hasAccount;
- (BOOL) hasLoginMode;
- (BOOL) hasVersion;
@property (readonly, retain) PP_Account* account;
@property (readonly) int32_t loginMode;
@property (readonly) int32_t version;

+ (PP_LoginPack*) defaultInstance;
- (PP_LoginPack*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PP_LoginPack_Builder*) builder;
+ (PP_LoginPack_Builder*) builder;
+ (PP_LoginPack_Builder*) builderWithPrototype:(PP_LoginPack*) prototype;
- (PP_LoginPack_Builder*) toBuilder;

+ (PP_LoginPack*) parseFromData:(NSData*) data;
+ (PP_LoginPack*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_LoginPack*) parseFromInputStream:(NSInputStream*) input;
+ (PP_LoginPack*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PP_LoginPack*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PP_LoginPack*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PP_LoginPack_Builder : PBGeneratedMessage_Builder {
@private
  PP_LoginPack* result;
}

- (PP_LoginPack*) defaultInstance;

- (PP_LoginPack_Builder*) clear;
- (PP_LoginPack_Builder*) clone;

- (PP_LoginPack*) build;
- (PP_LoginPack*) buildPartial;

- (PP_LoginPack_Builder*) mergeFrom:(PP_LoginPack*) other;
- (PP_LoginPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PP_LoginPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAccount;
- (PP_Account*) account;
- (PP_LoginPack_Builder*) setAccount:(PP_Account*) value;
- (PP_LoginPack_Builder*) setAccountBuilder:(PP_Account_Builder*) builderForValue;
- (PP_LoginPack_Builder*) mergeAccount:(PP_Account*) value;
- (PP_LoginPack_Builder*) clearAccount;

- (BOOL) hasLoginMode;
- (int32_t) loginMode;
- (PP_LoginPack_Builder*) setLoginMode:(int32_t) value;
- (PP_LoginPack_Builder*) clearLoginMode;

- (BOOL) hasVersion;
- (int32_t) version;
- (PP_LoginPack_Builder*) setVersion:(int32_t) value;
- (PP_LoginPack_Builder*) clearVersion;
@end

