// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PP_RegistPack.pb.h"

@implementation PpRegistPackRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PpRegistPackRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [PpAccountRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PP_RegistPack ()
@property (retain) PP_Account* account;
@property (retain) NSString* nickname;
@property (retain) NSString* avatarImg;
@end

@implementation PP_RegistPack

- (BOOL) hasAccount {
  return !!hasAccount_;
}
- (void) setHasAccount:(BOOL) value_ {
  hasAccount_ = !!value_;
}
@synthesize account;
- (BOOL) hasNickname {
  return !!hasNickname_;
}
- (void) setHasNickname:(BOOL) value_ {
  hasNickname_ = !!value_;
}
@synthesize nickname;
- (BOOL) hasAvatarImg {
  return !!hasAvatarImg_;
}
- (void) setHasAvatarImg:(BOOL) value_ {
  hasAvatarImg_ = !!value_;
}
@synthesize avatarImg;
- (void) dealloc {
  self.account = nil;
  self.nickname = nil;
  self.avatarImg = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.account = [PP_Account defaultInstance];
    self.nickname = @"";
    self.avatarImg = @"";
  }
  return self;
}
static PP_RegistPack* defaultPP_RegistPackInstance = nil;
+ (void) initialize {
  if (self == [PP_RegistPack class]) {
    defaultPP_RegistPackInstance = [[PP_RegistPack alloc] init];
  }
}
+ (PP_RegistPack*) defaultInstance {
  return defaultPP_RegistPackInstance;
}
- (PP_RegistPack*) defaultInstance {
  return defaultPP_RegistPackInstance;
}
- (BOOL) isInitialized {
  if (self.hasAccount) {
    if (!self.account.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAccount) {
    [output writeMessage:1 value:self.account];
  }
  if (self.hasNickname) {
    [output writeString:2 value:self.nickname];
  }
  if (self.hasAvatarImg) {
    [output writeString:3 value:self.avatarImg];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasAccount) {
    size_ += computeMessageSize(1, self.account);
  }
  if (self.hasNickname) {
    size_ += computeStringSize(2, self.nickname);
  }
  if (self.hasAvatarImg) {
    size_ += computeStringSize(3, self.avatarImg);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PP_RegistPack*) parseFromData:(NSData*) data {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromData:data] build];
}
+ (PP_RegistPack*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PP_RegistPack*) parseFromInputStream:(NSInputStream*) input {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromInputStream:input] build];
}
+ (PP_RegistPack*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_RegistPack*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromCodedInputStream:input] build];
}
+ (PP_RegistPack*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PP_RegistPack*)[[[PP_RegistPack builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PP_RegistPack_Builder*) builder {
  return [[[PP_RegistPack_Builder alloc] init] autorelease];
}
+ (PP_RegistPack_Builder*) builderWithPrototype:(PP_RegistPack*) prototype {
  return [[PP_RegistPack builder] mergeFrom:prototype];
}
- (PP_RegistPack_Builder*) builder {
  return [PP_RegistPack builder];
}
- (PP_RegistPack_Builder*) toBuilder {
  return [PP_RegistPack builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasAccount) {
    [output appendFormat:@"%@%@ {\n", indent, @"account"];
    [self.account writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasNickname) {
    [output appendFormat:@"%@%@: %@\n", indent, @"nickname", self.nickname];
  }
  if (self.hasAvatarImg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"avatarImg", self.avatarImg];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PP_RegistPack class]]) {
    return NO;
  }
  PP_RegistPack *otherMessage = other;
  return
      self.hasAccount == otherMessage.hasAccount &&
      (!self.hasAccount || [self.account isEqual:otherMessage.account]) &&
      self.hasNickname == otherMessage.hasNickname &&
      (!self.hasNickname || [self.nickname isEqual:otherMessage.nickname]) &&
      self.hasAvatarImg == otherMessage.hasAvatarImg &&
      (!self.hasAvatarImg || [self.avatarImg isEqual:otherMessage.avatarImg]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasAccount) {
    hashCode = hashCode * 31 + [self.account hash];
  }
  if (self.hasNickname) {
    hashCode = hashCode * 31 + [self.nickname hash];
  }
  if (self.hasAvatarImg) {
    hashCode = hashCode * 31 + [self.avatarImg hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PP_RegistPack_Builder()
@property (retain) PP_RegistPack* result;
@end

@implementation PP_RegistPack_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PP_RegistPack alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PP_RegistPack_Builder*) clear {
  self.result = [[[PP_RegistPack alloc] init] autorelease];
  return self;
}
- (PP_RegistPack_Builder*) clone {
  return [PP_RegistPack builderWithPrototype:result];
}
- (PP_RegistPack*) defaultInstance {
  return [PP_RegistPack defaultInstance];
}
- (PP_RegistPack*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PP_RegistPack*) buildPartial {
  PP_RegistPack* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PP_RegistPack_Builder*) mergeFrom:(PP_RegistPack*) other {
  if (other == [PP_RegistPack defaultInstance]) {
    return self;
  }
  if (other.hasAccount) {
    [self mergeAccount:other.account];
  }
  if (other.hasNickname) {
    [self setNickname:other.nickname];
  }
  if (other.hasAvatarImg) {
    [self setAvatarImg:other.avatarImg];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PP_RegistPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PP_RegistPack_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PP_Account_Builder* subBuilder = [PP_Account builder];
        if (self.hasAccount) {
          [subBuilder mergeFrom:self.account];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setAccount:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        [self setNickname:[input readString]];
        break;
      }
      case 26: {
        [self setAvatarImg:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAccount {
  return result.hasAccount;
}
- (PP_Account*) account {
  return result.account;
}
- (PP_RegistPack_Builder*) setAccount:(PP_Account*) value {
  result.hasAccount = YES;
  result.account = value;
  return self;
}
- (PP_RegistPack_Builder*) setAccountBuilder:(PP_Account_Builder*) builderForValue {
  return [self setAccount:[builderForValue build]];
}
- (PP_RegistPack_Builder*) mergeAccount:(PP_Account*) value {
  if (result.hasAccount &&
      result.account != [PP_Account defaultInstance]) {
    result.account =
      [[[PP_Account builderWithPrototype:result.account] mergeFrom:value] buildPartial];
  } else {
    result.account = value;
  }
  result.hasAccount = YES;
  return self;
}
- (PP_RegistPack_Builder*) clearAccount {
  result.hasAccount = NO;
  result.account = [PP_Account defaultInstance];
  return self;
}
- (BOOL) hasNickname {
  return result.hasNickname;
}
- (NSString*) nickname {
  return result.nickname;
}
- (PP_RegistPack_Builder*) setNickname:(NSString*) value {
  result.hasNickname = YES;
  result.nickname = value;
  return self;
}
- (PP_RegistPack_Builder*) clearNickname {
  result.hasNickname = NO;
  result.nickname = @"";
  return self;
}
- (BOOL) hasAvatarImg {
  return result.hasAvatarImg;
}
- (NSString*) avatarImg {
  return result.avatarImg;
}
- (PP_RegistPack_Builder*) setAvatarImg:(NSString*) value {
  result.hasAvatarImg = YES;
  result.avatarImg = value;
  return self;
}
- (PP_RegistPack_Builder*) clearAvatarImg {
  result.hasAvatarImg = NO;
  result.avatarImg = @"";
  return self;
}
@end

